-- - - - - - - - - VIEWS - - - - - - - - - 

CREATE OR REPLACE FORCE EDITIONABLE VIEW VIEW_RGSEAA_KEYS_ACTIVITIES_CATEGORIES_SUB_ACTIVITIES (
"RGSEAA_ID", "NUM_RGSEAA", "KEY_ID", "KEY_NAME", "ACTIVITY_ID", "ACTIVITY_NAME", "CATEGORY_ID", "CATEGORY_NAME", "SUB_ACTIVITY_ID", "SUB_ACTIVITY_NAME") DEFAULT COLLATION "BINARY_AI"  AS 
  SELECT R.ID AS RGSEAA_ID,
  R.NUM_RGSEAA AS NUM_RGSEAA, 
  K.ID AS KEY_ID,
  K.NAME AS KEY_NAME,
  A.ID AS ACTIVITY_ID,
  A.NAME AS ACTIVITY_NAME,
  C.ID AS CATEGORY_ID,
  C.NAME AS CATEGORY_NAME,
  SA.ID AS SUB_ACTIVITY_ID,
  SA.NAME AS SUB_ACTIVITY_NAME
FROM RGSEAA R
  JOIN RGSEAA_ACTIVITIES_PENDIENTE_REVISAR_EN_BACKEND RA ON R.ID = RA.RGSEAA_ID
  RIGHT JOIN ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES AKCSA ON AKCSA.ID = RA.ACTIVITY_KEY_CATEGORY_SUB_ACTIVITY_ID
  JOIN SUB_ACTIVITIES SA ON AKCSA.SUB_ACTIVITY_ID = SA.ID
  JOIN ACTIVITIES_KEYS_CATEGORIES AKC ON AKC.ID = AKCSA.ACTIVITY_KEY_CATEGORY_ID
  JOIN CATEGORIES C ON C.ID = AKC.CATEGORY_ID
  JOIN ACTIVITIES_KEYS AK ON AKC.ACTIVITY_KEY_ID = AK.ID
  JOIN ACTIVITIES A ON AK.ACTIVITY_ID = A.ID
  JOIN KEYS K ON AK.KEY_ID = K.ID;
