CREATE SEQUENCE SEQ_ACTIVITIES START WITH 1 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_ACTIVITIES_KEYS START WITH 1 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_ACTIVITIES_KEYS_CATEGORIES START WITH 1 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES START WITH 1 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_ACTUATIONS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_AUTHORIZATIONS START WITH 100 INCREMENT BY 1 CACHE 30;

CREATE SEQUENCE SEQ_CATEGORIES START WITH 1 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_CCAA START WITH 1 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_COMPANIES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_COMPETENT_AUTHORITIES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_COUNTRIES START WITH 1 INCREMENT BY 1 CACHE 30;

CREATE SEQUENCE SEQ_DENOMINATION_SALES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_DOCUMENTS START WITH 100 INCREMENT BY 1 CACHE 30;

CREATE SEQUENCE SEQ_ENTITIES START WITH 1 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_ENTITIES_TYPES START WITH 1 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_ESTABLISHMENTS START WITH 100 INCREMENT BY 1 CACHE 30;

CREATE SEQUENCE SEQ_FEES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_FORM_PRESENTATION START WITH 100 INCREMENT BY 1 CACHE 30;

CREATE SEQUENCE SEQ_KEYS START WITH 1 INCREMENT BY 1 CACHE 30;

CREATE SEQUENCE SEQ_LOCATIONS START WITH 1 INCREMENT BY 1 CACHE 30;

CREATE SEQUENCE SEQ_MODULES START WITH 1 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_MODULES_TYPES START WITH 1 INCREMENT BY 1 CACHE 30;

CREATE SEQUENCE SEQ_PERMISSIONS START WITH 1 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_PROFILES START WITH 1 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_PROFILES_PERMISSIONS START WITH 1 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_PROVINCES START WITH 1 INCREMENT BY 1 CACHE 30;

CREATE SEQUENCE SEQ_RGSEAA START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_RGSEAA_ACTIVITIES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_RGSEAA_AUTHORIZATIONS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_RGSEAA_FEES START WITH 100 INCREMENT BY 1 CACHE 30;

CREATE SEQUENCE SEQ_SITUATIONS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_SUB_ACTIVITIES START WITH 1 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_SUBSTANCES START WITH 100 INCREMENT BY 1 CACHE 30;

CREATE SEQUENCE SEQ_TYPES_ACTUATIONS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_TYPES_CHANGES_EXPEDIENTS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_TYPES_DOCUMENTS START WITH 100 INCREMENT BY 1 CACHE 30;

CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_USERS_ENTITIES START WITH 1 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_USERS_MODULES START WITH 1 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_USERS_PROFILES START WITH 1 INCREMENT BY 1 CACHE 30;


CREATE TABLE USERS
(
    ID             NUMBER(12) DEFAULT SEQ_USERS.nextval NOT NULL,
    NIF            VARCHAR2(9 char),
    NAME           VARCHAR2(255 char),
    FIRST_SURNAME  VARCHAR2(255 char),
    SECOND_SURNAME VARCHAR2(255 char),
    EMAIL          VARCHAR2(255 char),
    PHONE          VARCHAR2(255 char),
    CREATED_AT     TIMESTAMP(6),
    CREATED_BY     NUMBER(32),
    UPDATED_AT     TIMESTAMP(6),
    UPDATED_BY     NUMBER(32),
    STATE          NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE USERS ADD CONSTRAINT PK_USERS__ID PRIMARY KEY (ID);
ALTER TABLE USERS ADD CONSTRAINT UK_USERS__NIF UNIQUE (NIF);
--ALTER TABLE USERS ADD CONSTRAINT FK_USERS__CREATED_BY_ID FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID);
--ALTER TABLE USERS ADD CONSTRAINT FK_USERS__UPDATED_BY_ID FOREIGN KEY (UPDATED_BY) REFERENCES USERS(ID);

CREATE TABLE AUTHORIZATIONS
(
    ID              NUMBER(12) DEFAULT SEQ_AUTHORIZATIONS.nextval NOT NULL,
    NAME            VARCHAR2(200) NOT NULL,
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE AUTHORIZATIONS ADD CONSTRAINT PK_AUTHORIZATIONS__ID PRIMARY KEY (ID);
--ALTER TABLE AUTHORIZATIONS ADD CONSTRAINT FK_AUTHORIZATIONS__CREATED_BY_ID FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID);
--ALTER TABLE AUTHORIZATIONS ADD CONSTRAINT FK_AUTHORIZATIONS__UPDATED_BY_ID FOREIGN KEY (UPDATED_BY) REFERENCES USERS(ID);


CREATE TABLE PERMISSIONS
(
    ID              NUMBER(12) DEFAULT SEQ_PERMISSIONS.nextval NOT NULL,
    CODE            VARCHAR2(100 char),
    DESCRIPTION     VARCHAR2(100 char),
    NAME            VARCHAR2(50 char) NOT NULL,
    CREATED_AT      TIMESTAMP(6),
    CREATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE PERMISSIONS ADD CONSTRAINT PK_PERMISSIONS__ID PRIMARY KEY (ID);
--ALTER TABLE PERMISSIONS ADD CONSTRAINT FK_PERMISSIONS__CREATED_BY_ID FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID);
--ALTER TABLE PERMISSIONS ADD CONSTRAINT FK_PERMISSIONS__UPDATED_BY_ID FOREIGN KEY (UPDATED_BY) REFERENCES USERS(ID);


CREATE TABLE PROFILES
(
    ID          NUMBER(12) DEFAULT SEQ_PROFILES.nextval NOT NULL,
    NAME        VARCHAR2(255 char) NOT NULL,
    CREATED_AT  TIMESTAMP(6),
    CREATED_BY  NUMBER(32),
    UPDATED_AT  TIMESTAMP(6),
    UPDATED_BY  NUMBER(32),
    STATE       NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE PROFILES ADD CONSTRAINT PK_PROFILES__ID PRIMARY KEY (ID);
--ALTER TABLE PROFILES ADD CONSTRAINT FK_PROFILES__CREATED_BY_ID FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID);
--ALTER TABLE PROFILES ADD CONSTRAINT FK_PROFILES__UPDATED_BY_ID FOREIGN KEY (UPDATED_BY) REFERENCES USERS(ID);


CREATE TABLE PROFILES_PERMISSIONS
(
    ID            NUMBER(12) DEFAULT SEQ_PROFILES_PERMISSIONS.nextval NOT NULL,
    PERMISSION_ID NUMBER(32) NOT NULL,
    PROFILE_ID    NUMBER(32) NOT NULL,
    CREATED_AT    TIMESTAMP(6) ,
    CREATED_BY    NUMBER(32),
    UPDATED_AT    TIMESTAMP(6) ,
    UPDATED_BY    NUMBER(32),
    STATE         NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE PROFILES_PERMISSIONS ADD CONSTRAINT PK_PROFILES_PERMISSIONS__ID PRIMARY KEY (ID);
ALTER TABLE PROFILES_PERMISSIONS ADD CONSTRAINT UK_PROFILES_PERMISSIONS__PERMISSION_ID__PROFILE_ID_UNIQUE UNIQUE (PERMISSION_ID,PROFILE_ID) ENABLE;
ALTER TABLE PROFILES_PERMISSIONS ADD CONSTRAINT FK_PROFILES_PERMISSIONS__PERMISSION_ID  FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(ID);
ALTER TABLE PROFILES_PERMISSIONS ADD CONSTRAINT FK_PROFILES_PERMISSIONS__PROFILE_ID     FOREIGN KEY (PROFILE_ID)    REFERENCES PROFILES(ID);
--ALTER TABLE PROFILES_PERMISSIONS ADD CONSTRAINT FK_PROFILES_PERMISSIONS__CREATED_BY_ID  FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE PROFILES_PERMISSIONS ADD CONSTRAINT FK_PROFILES_PERMISSIONS__UPDATED_BY_ID  FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);


CREATE TABLE ENTITIES_TYPES
(
    ID              NUMBER(12) DEFAULT SEQ_ENTITIES_TYPES.nextval NOT NULL,
    DESCRIPTION     VARCHAR2(255 char),
    NAME            VARCHAR2(255 char) NOT NULL,
    CREATED_AT      TIMESTAMP(6),
    CREATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE ENTITIES_TYPES ADD CONSTRAINT PK_ENTITIES_TYPES__ID PRIMARY KEY (ID);
--ALTER TABLE ENTITIES_TYPES ADD CONSTRAINT FK_ENTITIES_TYPES__CREATED_BY_ID FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID);
--ALTER TABLE ENTITIES_TYPES ADD CONSTRAINT FK_ENTITIES_TYPES__UPDATED_BY_ID FOREIGN KEY (UPDATED_BY) REFERENCES USERS(ID);


CREATE TABLE ENTITIES
(
    ID              NUMBER(12) DEFAULT SEQ_ENTITIES.nextval NOT NULL,
    NAME            VARCHAR2(100 char) NOT NULL,
    DESCRIPTION     VARCHAR2(100 char) NOT NULL,
    CODE            VARCHAR2(6 char) NOT NULL,
    TYPE_ID         NUMBER(32)  NOT NULL,
    ADDRESS         VARCHAR2(255 char),
    CONTACT_PERSON  VARCHAR2(255 char),
    EMAIL           VARCHAR2(255 char),
    PHONE           VARCHAR2(255 char),
    POSTAL_CODE     VARCHAR2(255 char),
    ROOT_ENTITY     NUMBER(1),
    CREATED_AT      TIMESTAMP(6),
    CREATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE ENTITIES ADD CONSTRAINT PK_ENTITIES__ID PRIMARY KEY (ID);
ALTER TABLE ENTITIES ADD CONSTRAINT UK_ENTITIES__CODE UNIQUE (CODE);
ALTER TABLE ENTITIES ADD CONSTRAINT FK_ENTITIES__ID_TYPE        FOREIGN KEY (TYPE_ID)       REFERENCES ENTITIES_TYPES(ID);
--ALTER TABLE ENTITIES ADD CONSTRAINT FK_ENTITIES__CREATED_BY_ID  FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE ENTITIES ADD CONSTRAINT FK_ENTITIES__UPDATED_BY_ID  FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);

CREATE TABLE USERS_ENTITIES
(
    ID          NUMBER(12) DEFAULT SEQ_USERS_ENTITIES.nextval NOT NULL,
    ENTITY_ID   NUMBER(12)  NOT NULL,
    USER_ID     NUMBER(12)  NOT NULL,
    SCOPE_CODE  VARCHAR2(20 char) NOT NULL,
    STATE       NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE USERS_ENTITIES ADD CONSTRAINT PK_USERS_ENTITIES__ID PRIMARY KEY (ID);
ALTER TABLE USERS_ENTITIES ADD CONSTRAINT UK_USERS_ENTITIES__ENTITY_ID__USER_ID_UNIQUE UNIQUE (ENTITY_ID,USER_ID) ENABLE;
ALTER TABLE USERS_ENTITIES ADD CONSTRAINT FK_USERS_ENTITIES__ENTITY_ID  FOREIGN KEY (ENTITY_ID) REFERENCES ENTITIES(ID);
ALTER TABLE USERS_ENTITIES ADD CONSTRAINT FK_USERS_ENTITIES__USER_ID    FOREIGN KEY (USER_ID)   REFERENCES USERS(ID);


CREATE TABLE MODULES_TYPES
(
    ID              NUMBER(12) DEFAULT SEQ_MODULES_TYPES.nextval  NOT NULL,
    NAME            VARCHAR2(100),
    DESCRIPTION     VARCHAR2(200),
    CREATED_AT      TIMESTAMP(6),
    CREATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE MODULES_TYPES ADD CONSTRAINT PK_MODULES_TYPES__ID PRIMARY KEY (ID);
--ALTER TABLE MODULES_TYPES ADD CONSTRAINT FK_MODULES_TYPES__CREATED_BY_ID  FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE MODULES_TYPES ADD CONSTRAINT FK_MODULES_TYPES__UPDATED_BY_ID  FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);


CREATE TABLE MODULES
(
    ID          NUMBER(12) DEFAULT SEQ_MODULES.nextval NOT NULL,
    CODE        VARCHAR2(6 char) NOT NULL,
    NAME        VARCHAR2(100),
    TYPE_ID     NUMBER(12),
    CREATED_AT  TIMESTAMP(6),
    CREATED_BY  NUMBER(32),
    UPDATED_AT  TIMESTAMP(6),
    UPDATED_BY  NUMBER(32),
    STATE       NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE MODULES ADD CONSTRAINT PK_MODULES__ID PRIMARY KEY (ID);
ALTER TABLE MODULES ADD CONSTRAINT UK_MODULES__CODE UNIQUE (CODE);
ALTER TABLE MODULES ADD CONSTRAINT FK_MODULES__ID_TYPE FOREIGN KEY (TYPE_ID) REFERENCES MODULES_TYPES(ID);
--ALTER TABLE MODULES ADD CONSTRAINT FK_MODULES__CREATED_BY_ID  FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE MODULES ADD CONSTRAINT FK_MODULES__UPDATED_BY_ID  FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);


CREATE TABLE USERS_MODULES
(
    ID         NUMBER(12) DEFAULT SEQ_USERS_MODULES.nextval NOT NULL,
    MODULE_ID  NUMBER(12),
    USER_ID    NUMBER(12),
    CREATED_AT TIMESTAMP(6),
    CREATED_BY NUMBER(32),
    UPDATED_AT TIMESTAMP(6),
    UPDATED_BY NUMBER(32),
    STATE      NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE USERS_MODULES ADD CONSTRAINT PK_USERS_MODULES_ID PRIMARY KEY (ID);
ALTER TABLE USERS_MODULES ADD CONSTRAINT UK_USERS_MODULES__MODULE_ID__USER_ID_UNIQUE UNIQUE (MODULE_ID,USER_ID) ENABLE;
ALTER TABLE USERS_MODULES ADD CONSTRAINT FK_USERS_MODULES__MODULE_ID      FOREIGN KEY (MODULE_ID)     REFERENCES MODULES(ID);
ALTER TABLE USERS_MODULES ADD CONSTRAINT FK_USERS_MODULES__USER_ID        FOREIGN KEY (USER_ID)       REFERENCES USERS(ID);
--ALTER TABLE USERS_MODULES ADD CONSTRAINT FK_USERS_MODULES__CREATED_BY_ID  FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE USERS_MODULES ADD CONSTRAINT FK_USERS_MODULES__UPDATED_BY_ID  FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);


CREATE TABLE USERS_PROFILES
(
    ID          NUMBER(12) DEFAULT SEQ_USERS_PROFILES.nextval NOT NULL,
    PROFILE_ID  NUMBER(12),
    USER_ID     NUMBER(12),
    CREATED_AT  TIMESTAMP(6),
    CREATED_BY  NUMBER(32),
    UPDATED_AT  TIMESTAMP(6),
    UPDATED_BY  NUMBER(12),
    STATE       NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE USERS_PROFILES ADD CONSTRAINT PK_USERS_PROFILES_ID PRIMARY KEY (ID);
ALTER TABLE USERS_PROFILES ADD CONSTRAINT UK_USERS_PROFILES__PROFILE_ID__USER_ID_UNIQUE UNIQUE (PROFILE_ID,USER_ID) ENABLE;
ALTER TABLE USERS_PROFILES ADD CONSTRAINT FK_USERS_PROFILES__PROFILE_ID     FOREIGN KEY (PROFILE_ID)    REFERENCES PROFILES(ID);
ALTER TABLE USERS_PROFILES ADD CONSTRAINT FK_USERS_PROFILES__USER_ID        FOREIGN KEY (USER_ID)       REFERENCES USERS(ID);
--ALTER TABLE USERS_PROFILES ADD CONSTRAINT FK_USERS_PROFILES__CREATED_BY_ID  FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE USERS_PROFILES ADD CONSTRAINT FK_USERS_PROFILES__UPDATED_BY_ID  FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);


CREATE TABLE COUNTRIES (
    ID                  NUMBER(32) default SEQ_COUNTRIES.nextval NOT NULL,
    NAME                VARCHAR2(50),
    ENROLLMENT          VARCHAR2(3),
    NO_DELETE           NUMBER,
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6),
    STATE               NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE COUNTRIES ADD CONSTRAINT PK_COUNTRIES__ID PRIMARY KEY (ID);
--ALTER TABLE COUNTRIES ADD CONSTRAINT FK_COUNTRIES__CREATED_BY_ID  FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE COUNTRIES ADD CONSTRAINT FK_COUNTRIES__UPDATED_BY_ID  FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);


CREATE TABLE CCAA (
    ID                  NUMBER(32) default SEQ_CCAA.nextval NOT NULL,
    NAME                VARCHAR2(50),
    ENROLLMENT          VARCHAR2(3),
    COUNTRY_ID          NUMBER(32) NOT NULL,
    NO_DELETE           NUMBER DEFAULT 1,
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6),
    STATE               NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE CCAA ADD CONSTRAINT PK_CCAA__ID PRIMARY KEY (ID);
ALTER TABLE CCAA ADD CONSTRAINT FK_CCAA__COUNTRY_ID  FOREIGN KEY (COUNTRY_ID)    REFERENCES COUNTRIES(ID);
--ALTER TABLE CCAA ADD CONSTRAINT FK_CCAA__CREATED_BY_ID  FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE CCAA ADD CONSTRAINT FK_CCAA__UPDATED_BY_ID  FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);


CREATE TABLE PROVINCES
(
    ID                  NUMBER(12) default SEQ_PROVINCES.nextval NOT NULL,
    NAME                VARCHAR2(30),
    ENROLLMENT          VARCHAR2(3),
    PRE_POSTAL_CODE     NUMBER(2),
    ADDRESS             VARCHAR2(500),
    CCAA_ID             NUMBER(12),
    CREATED_AT          TIMESTAMP(6),
    CREATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    STATE               NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE PROVINCES ADD CONSTRAINT PK_PROVINCES__ID PRIMARY KEY (ID);
ALTER TABLE PROVINCES ADD CONSTRAINT FK_PROVINCES__CCAA_ID  FOREIGN KEY (CCAA_ID)    REFERENCES CCAA(ID);
--ALTER TABLE PROVINCES ADD CONSTRAINT FK_PROVINCES__CREATED_BY_ID  FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE PROVINCES ADD CONSTRAINT FK_PROVINCES__UPDATED_BY_ID  FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);


CREATE TABLE LOCATIONS
(
    ID                      NUMBER(12) DEFAULT  SEQ_LOCATIONS.nextval NOT NULL,
    NAME                    VARCHAR2(200),
    DESCRIPTION_PADRE       VARCHAR2(200),
    COMBO                   NUMBER,
    PROVINCE_ID             NUMBER(12),
    PADRE_ID                NUMBER(12),
    INE_CODE                VARCHAR2(12),
    CREATED_AT              TIMESTAMP(6),
    CREATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE LOCATIONS ADD CONSTRAINT PK_LOCATIONS__ID PRIMARY KEY (ID);
ALTER TABLE LOCATIONS ADD CONSTRAINT FK_LOCATIONS__PROVINCE_ID  FOREIGN KEY (PROVINCE_ID)    REFERENCES PROVINCES(ID);
--ALTER TABLE LOCATIONS ADD CONSTRAINT FK_LOCATIONS__CREATED_BY_ID  FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE LOCATIONS ADD CONSTRAINT FK_LOCATIONS__UPDATED_BY_ID  FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);


CREATE TABLE SITUATIONS (
    ID                      NUMBER(12) DEFAULT SEQ_SITUATIONS.nextval NOT NULL,
    CODE                    NUMBER,
    NAME                    VARCHAR2(50),
    TYPE_COMPANY_PRODUCT   NUMBER(1),
--    NEW_OPTION              NUMBER,
    VISIBLE_RGSA            NUMBER DEFAULT 1,
    VISIBLE_UE              NUMBER DEFAULT 1,
    CREATED_BY              NUMBER(32),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE SITUATIONS ADD CONSTRAINT PK_SITUATION__ID PRIMARY KEY (ID);
--ALTER TABLE SITUATIONS ADD CONSTRAINT FK_SITUATIONS__CREATED_BY_ID  FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE SITUATIONS ADD CONSTRAINT FK_SITUATIONS__UPDATED_BY_ID  FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);


CREATE TABLE COMPETENT_AUTHORITIES (
    ID                      NUMBER(12) DEFAULT SEQ_COMPETENT_AUTHORITIES.nextval NOT NULL,
    CODE                    VARCHAR2(10),
    NAME                    VARCHAR2(50),
    CREATED_BY              NUMBER(32),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE COMPETENT_AUTHORITIES ADD CONSTRAINT PK_COMPETENT_AUTHORITIES__ID PRIMARY KEY (ID);
--ALTER TABLE COMPETENT_AUTHORITIES ADD CONSTRAINT FK_COMPETENT_AUTHORITIES__CREATED_BY_ID  FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE COMPETENT_AUTHORITIES ADD CONSTRAINT FK_COMPETENT_AUTHORITIES__UPDATED_BY_ID  FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);


CREATE TABLE COMPANIES
(
    ID                      NUMBER(12) DEFAULT SEQ_COMPANIES.nextval NOT NULL,
    NIF                     VARCHAR2(20),
    NAME                    VARCHAR2(200),
    EMAIL                   VARCHAR2(50),
    PAGE_WEB                VARCHAR2(200),
    OBSERVATION             VARCHAR2(2000),
    SITUATION_ID            NUMBER(12),
    ADDRESS                 VARCHAR2(500),
    POSTAL_CODE             VARCHAR2(20),
    COUNTRY_ID              NUMBER(12),
    CCAA_ID                 NUMBER(32),
    PROVINCE_ID             NUMBER(12),
    LOCATION_ID             NUMBER(12),
    CREATED_BY              NUMBER(12),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(12),
    UPDATED_AT              TIMESTAMP(6),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE COMPANIES ADD CONSTRAINT PK_COMPANIES__ID PRIMARY KEY (ID);
ALTER TABLE COMPANIES ADD CONSTRAINT FK_COMPANIES__SITUATION_ID    FOREIGN KEY (SITUATION_ID)  REFERENCES SITUATIONS(ID);
ALTER TABLE COMPANIES ADD CONSTRAINT FK_COMPANIES__COUNTRY_ID      FOREIGN KEY (COUNTRY_ID)    REFERENCES COUNTRIES(ID);
ALTER TABLE COMPANIES ADD CONSTRAINT FK_COMPANIES__CCAA_ID         FOREIGN KEY (CCAA_ID)       REFERENCES CCAA(ID);
ALTER TABLE COMPANIES ADD CONSTRAINT FK_COMPANIES__PROVINCE_ID     FOREIGN KEY (PROVINCE_ID)   REFERENCES PROVINCES(ID);
ALTER TABLE COMPANIES ADD CONSTRAINT FK_COMPANIES__LOCATION_ID     FOREIGN KEY (LOCATION_ID)   REFERENCES LOCATIONS(ID);
--ALTER TABLE COMPANIES ADD CONSTRAINT FK_COMPANIES__CREATED_BY_ID    FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE COMPANIES ADD CONSTRAINT FK_COMPANIES__UPDATED_BY_ID    FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);


CREATE TABLE ESTABLISHMENTS
(
    ID                      NUMBER(12) default SEQ_ESTABLISHMENTS.nextval NOT NULL,
    COMPANY_ID              NUMBER(12) NOT NULL,
    ADDRESS                 VARCHAR2(500),
    POSTAL_CODE             VARCHAR2(20),
    COUNTRY_ID              NUMBER(12),
    CCAA_ID                 NUMBER(32),
    PROVINCE_ID             NUMBER(12),
    LOCATION_ID             NUMBER(12),
    SITUATION_ID            NUMBER(12),
    CREATED_BY              NUMBER(12),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(12),
    UPDATED_AT              TIMESTAMP(6),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE ESTABLISHMENTS ADD CONSTRAINT PK_ESTABLISHMENTS__ID PRIMARY KEY (ID);
ALTER TABLE ESTABLISHMENTS ADD CONSTRAINT FK_ESTABLISHMENTS__COUNTRY_ID     FOREIGN KEY (COUNTRY_ID)    REFERENCES COUNTRIES(ID);
ALTER TABLE ESTABLISHMENTS ADD CONSTRAINT FK_ESTABLISHMENTS__CCAA_ID        FOREIGN KEY (CCAA_ID)       REFERENCES CCAA(ID);
ALTER TABLE ESTABLISHMENTS ADD CONSTRAINT FK_ESTABLISHMENTS__PROVINCE_ID    FOREIGN KEY (PROVINCE_ID)   REFERENCES PROVINCES(ID);
ALTER TABLE ESTABLISHMENTS ADD CONSTRAINT FK_ESTABLISHMENTS__LOCATION_ID    FOREIGN KEY (LOCATION_ID)   REFERENCES LOCATIONS(ID);
ALTER TABLE ESTABLISHMENTS ADD CONSTRAINT FK_ESTABLISHMENTS__SITUATION_ID   FOREIGN KEY (SITUATION_ID)  REFERENCES SITUATIONS(ID);
--ALTER TABLE ESTABLISHMENTS ADD CONSTRAINT FK_ESTABLISHMENTS__CREATED_BY_ID  FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE ESTABLISHMENTS ADD CONSTRAINT FK_ESTABLISHMENTS__UPDATED_BY_ID  FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);


CREATE TABLE TYPES_ACTUATIONS
(
    ID                      NUMBER(12) DEFAULT SEQ_TYPES_ACTUATIONS.nextval NOT NULL,
    NAME                    VARCHAR2(250),
    TYPE_COMPANY_PRODUCT   NUMBER (1),
    VISIBLE_CCAA            NUMBER,
    CREATED_BY              NUMBER(32),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE TYPES_ACTUATIONS ADD CONSTRAINT PK_TYPES_ACTUATIONS__ID PRIMARY KEY (ID);
--ALTER TABLE TYPES_ACTUATIONS ADD CONSTRAINT FK_TYPES_ACTUATIONS__CREATED_BY_ID  FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE TYPES_ACTUATIONS ADD CONSTRAINT FK_TYPES_ACTUATIONS__UPDATED_BY_ID  FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);


CREATE TABLE ACTUATIONS
(
    ID                  NUMBER(12) default SEQ_ACTUATIONS.nextval NOT NULL,
    COMPANY_ID          NUMBER(12),
    ESTABLISHMENT_ID    NUMBER(12),
    TYPE_ACTUATION_ID   NUMBER(12),
    PRODUCT_ID          NUMBER(12),
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6),
    STATE               NUMBER(1)  DEFAULT 1 NOT NULL
);
ALTER TABLE ACTUATIONS ADD CONSTRAINT PK_ACTUATIONS__ID PRIMARY KEY (ID);
ALTER TABLE ACTUATIONS ADD CONSTRAINT FK_ACTUATIONS__COMPANY_ID         FOREIGN KEY (COMPANY_ID)        REFERENCES COMPANIES(ID);
ALTER TABLE ACTUATIONS ADD CONSTRAINT FK_ACTUATIONS__ESTABLISHMENT_ID   FOREIGN KEY (ESTABLISHMENT_ID)  REFERENCES ESTABLISHMENTS(ID);
ALTER TABLE ACTUATIONS ADD CONSTRAINT FK_ACTUATIONS__TYPE_ACTUATION_ID  FOREIGN KEY (TYPE_ACTUATION_ID) REFERENCES TYPES_ACTUATIONS(ID);
--ALTER TABLE ACTUATIONS ADD CONSTRAINT FK_ACTUATIONS__CREATED_BY_ID  FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE ACTUATIONS ADD CONSTRAINT FK_ACTUATIONS__UPDATED_BY_ID  FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);


CREATE TABLE TYPES_DOCUMENTS
(
    ID                      NUMBER(12) DEFAULT SEQ_TYPES_DOCUMENTS.nextval NOT NULL,
    TYPE                    VARCHAR2(20),
    NAME                    VARCHAR2(200),
    TYPE_COMPANY_PRODUCT    NUMBER(32),
    VISIBLE_CCAA            NUMBER,
    NO_DELETE               NUMBER,
    CREATED_BY              NUMBER(32),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE TYPES_DOCUMENTS ADD CONSTRAINT PK_TYPES_DOCUMENTS__ID PRIMARY KEY (ID);
--ALTER TABLE TYPES_DOCUMENTS ADD CONSTRAINT FK_TYPES_DOCUMENTS__CREATED_BY_ID    FOREIGN KEY (CREATED_BY)        REFERENCES USERS(ID);
--ALTER TABLE TYPES_DOCUMENTS ADD CONSTRAINT FK_TYPES_DOCUMENTS__UPDATED_BY_ID    FOREIGN KEY (UPDATED_BY)        REFERENCES USERS(ID);



CREATE TABLE DOCUMENTS
(
    ID                      NUMBER(32) DEFAULT SEQ_DOCUMENTS.nextval NOT NULL,
    NAME                    VARCHAR2(200),
    TYPE_FILE_ID            NUMBER(12),
    COMPANY_ID              NUMBER(12),
    ACTUATION_ID               NUMBER(12),
    TYPE_DOCUMENT_ID        NUMBER(12),
    PRODUCT_ID              NUMBER(12),
    CASE_FILE_ID            NUMBER(12),
    NUMBER_EXIT             VARCHAR2(25),
    PATH_FILE               VARCHAR2(200),
    PATH_FILE_OLD           VARCHAR2(200),
    NAME_FILE               VARCHAR2(1000),
    CREATED_BY              NUMBER(32),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE DOCUMENTS ADD CONSTRAINT PK_DOCUMENTS__ID PRIMARY KEY (ID);
ALTER TABLE DOCUMENTS ADD CONSTRAINT FK_DOCUMENTS__COMPANY_ID       FOREIGN KEY (COMPANY_ID)        REFERENCES COMPANIES(ID);
ALTER TABLE DOCUMENTS ADD CONSTRAINT FK_DOCUMENTS__ACTUATION_ID        FOREIGN KEY (ACTUATION_ID)         REFERENCES ACTUATIONS(ID);
ALTER TABLE DOCUMENTS ADD CONSTRAINT FK_DOCUMENTS__TYPE_DOCUMENT_ID FOREIGN KEY (TYPE_DOCUMENT_ID)  REFERENCES TYPES_DOCUMENTS(ID);
--ALTER TABLE DOCUMENTS ADD CONSTRAINT FK_DOCUMENTS__CREATED_BY_ID    FOREIGN KEY (CREATED_BY)        REFERENCES USERS(ID);
--ALTER TABLE DOCUMENTS ADD CONSTRAINT FK_DOCUMENTS__UPDATED_BY_ID    FOREIGN KEY (UPDATED_BY)        REFERENCES USERS(ID);


CREATE TABLE TYPES_CHANGES_EXPEDIENTS
(
    ID              NUMBER(12) DEFAULT SEQ_TYPES_CHANGES_EXPEDIENTS.nextval NOT NULL,
    NAME            VARCHAR2(250),
    CREATED_AT      TIMESTAMP(6),
    CREATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE TYPES_CHANGES_EXPEDIENTS ADD CONSTRAINT PK_TYPES_CHANGES_EXPEDIENTS__ID PRIMARY KEY (ID);
--ALTER TABLE TYPES_CHANGES_EXPEDIENTS ADD CONSTRAINT FK_TYPES_CHANGES_EXPEDIENTS__CREATED_BY_ID    FOREIGN KEY (CREATED_BY)        REFERENCES USERS(ID);
--ALTER TABLE TYPES_CHANGES_EXPEDIENTS ADD CONSTRAINT FK_TYPES_CHANGES_EXPEDIENTS__UPDATED_BY_ID    FOREIGN KEY (UPDATED_BY)        REFERENCES USERS(ID);


CREATE TABLE CATEGORIES (
    ID              NUMBER(12) DEFAULT SEQ_CATEGORIES.NEXTVAL NOT NULL,
    CODE            NUMBER(3),
    NAME            VARCHAR2(200),
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE CATEGORIES ADD CONSTRAINT PK_CATEGORIES__ID PRIMARY KEY (ID);
--ALTER TABLE CATEGORIES ADD CONSTRAINT FK_CATEGORIES__CREATED_BY_ID    FOREIGN KEY (CREATED_BY)        REFERENCES USERS(ID);
--ALTER TABLE CATEGORIES ADD CONSTRAINT FK_CATEGORIES__UPDATED_BY_ID    FOREIGN KEY (UPDATED_BY)        REFERENCES USERS(ID);


CREATE TABLE AUTH_USER_REQUEST
(
    PETITION_ID        VARCHAR2(36)   NOT NULL,
    RELAY_ID           VARCHAR2(20)   NOT NULL,
    TOKEN              VARCHAR2(4000) NOT NULL,
    EXP                NUMBER(38)     NOT NULL,
    PROCESS_RETURN_URL VARCHAR2(4000) NOT NULL
);
ALTER TABLE AUTH_USER_REQUEST ADD CONSTRAINT PK_AUTH_USER_REQUEST__PETITION_ID PRIMARY KEY (PETITION_ID);
ALTER TABLE AUTH_USER_REQUEST ADD CONSTRAINT UK_AUTH_USER_REQUEST__PETITION_ID__RELAY_ID_UNIQUE UNIQUE (PETITION_ID,RELAY_ID) ENABLE;



CREATE TABLE AUTH_USER_TOKEN
(
    PETITION_ID VARCHAR2(36)   NOT NULL,
    RELAY_ID    VARCHAR2(20)   NOT NULL,
    DOC_NUM     VARCHAR2(50)   NOT NULL,
    TOKEN       VARCHAR2(4000) NOT NULL,
    EXP         NUMBER(38)     NOT NULL
);
ALTER TABLE AUTH_USER_TOKEN ADD CONSTRAINT PK_AUTH_USER_TOKEN__PETITION_ID PRIMARY KEY (PETITION_ID);
ALTER TABLE AUTH_USER_TOKEN ADD CONSTRAINT UK_AUTH_USER_TOKEN__PETITION_ID__RELAY_ID_UNIQUE UNIQUE (PETITION_ID,RELAY_ID) ENABLE;



CREATE TABLE KEYS (
    ID                  NUMBER(12) DEFAULT SEQ_KEYS.nextval NOT NULL,
    CODE                NUMBER(3),
    NAME                VARCHAR2(200),
    DATE_REGISTER       DATE,
    DATE_UNREGISTER     DATE,
    ALLOW_PRODUCT       NUMBER,
    IS_OLD              NUMBER DEFAULT 0,
    IS_PUBLIC           NUMBER DEFAULT 1,
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6),
    STATE               NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE KEYS ADD CONSTRAINT PK_KEYS__ID PRIMARY KEY (ID);
--ALTER TABLE KEYS ADD CONSTRAINT FK_KEYS__CREATED_BY_ID    FOREIGN KEY (CREATED_BY)        REFERENCES USERS(ID);
--ALTER TABLE KEYS ADD CONSTRAINT FK_KEYS__UPDATED_BY_ID    FOREIGN KEY (UPDATED_BY)        REFERENCES USERS(ID);


CREATE TABLE ACTIVITIES
(
    ID                  NUMBER(12) DEFAULT SEQ_ACTIVITIES.nextval NOT NULL,
    CODE                NUMBER(3),
    NAME                VARCHAR2(250),
    IS_PUBLIC           NUMBER DEFAULT 1 NOT NULL,
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6),
    STATE               NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE ACTIVITIES ADD CONSTRAINT PK_ACTIVITIES__ID PRIMARY KEY (ID);
--ALTER TABLE ACTIVITIES ADD CONSTRAINT FK_ACTIVITIES__CREATED_BY_ID    FOREIGN KEY (CREATED_BY)        REFERENCES USERS(ID);
--ALTER TABLE ACTIVITIES ADD CONSTRAINT FK_ACTIVITIES__UPDATED_BY_ID    FOREIGN KEY (UPDATED_BY)        REFERENCES USERS(ID);


CREATE TABLE DENOMINATION_SALES (
    ID              NUMBER(12) DEFAULT SEQ_DENOMINATION_SALES.nextval NOT NULL,
    NAME            VARCHAR2(200),
    KEY_ID          NUMBER(12),
    ACTIVITY_ID     NUMBER(12),
    FILE_TYPE       VARCHAR2(5),
    IS_PUBLIC       NUMBER(1) DEFAULT 0,
    DATE_REGISTER   DATE,
    DATE_UNREGISTER DATE,
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE DENOMINATION_SALES ADD CONSTRAINT PK_DENOMINATION_SALES__ID PRIMARY KEY (ID);
ALTER TABLE DENOMINATION_SALES ADD CONSTRAINT UK_DENOMINATION_SALES__KEY_ID__ACTIVITY_ID_UNIQUE UNIQUE (KEY_ID,ACTIVITY_ID) ENABLE;
ALTER TABLE DENOMINATION_SALES ADD CONSTRAINT FK_DENOMINATION_SALES__KEY_ID             FOREIGN KEY (KEY_ID)            REFERENCES KEYS(ID);
ALTER TABLE DENOMINATION_SALES ADD CONSTRAINT FK_DENOMINATION_SALES__ACTIVITY_ID        FOREIGN KEY (ACTIVITY_ID)       REFERENCES ACTIVITIES(ID);
--ALTER TABLE DENOMINATION_SALES ADD CONSTRAINT FK_DENOMINATION_SALES__CREATED_BY_ID      FOREIGN KEY (CREATED_BY)        REFERENCES USERS(ID);
--ALTER TABLE DENOMINATION_SALES ADD CONSTRAINT FK_DENOMINATION_SALES__UPDATED_BY_ID      FOREIGN KEY (UPDATED_BY)        REFERENCES USERS(ID);


CREATE TABLE SUB_ACTIVITIES
(
    ID              NUMBER(12) DEFAULT SEQ_SUB_ACTIVITIES.NEXTVAL NOT NULL,
    CODE            NUMBER(32),
    NAME            VARCHAR2(250),
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE SUB_ACTIVITIES ADD CONSTRAINT PK_SUB_ACTIVITIES__ID PRIMARY KEY (ID);
--ALTER TABLE SUB_ACTIVITIES ADD CONSTRAINT FK_SUB_ACTIVITIES__CREATED_BY_ID    FOREIGN KEY (CREATED_BY)        REFERENCES USERS(ID);
--ALTER TABLE SUB_ACTIVITIES ADD CONSTRAINT FK_SUB_ACTIVITIES__UPDATED_BY_ID    FOREIGN KEY (UPDATED_BY)        REFERENCES USERS(ID);


CREATE TABLE ACTIVITIES_KEYS (
    ID              NUMBER(12) DEFAULT SEQ_ACTIVITIES_KEYS.nextval  NOT NULL,
    KEY_ID          NUMBER(12) NOT NULL,
    ACTIVITY_ID     NUMBER(12) NOT NULL,
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE ACTIVITIES_KEYS ADD CONSTRAINT PK_ACTIVITIES_KEYS__ID PRIMARY KEY (ID);
ALTER TABLE ACTIVITIES_KEYS ADD CONSTRAINT UK_ACTIVITIES_KEYS__KEY_ID__ACTIVITY_ID_UNIQUE UNIQUE (KEY_ID,ACTIVITY_ID) ENABLE;
ALTER TABLE ACTIVITIES_KEYS ADD CONSTRAINT FK_ACTIVITIES_KEYS__KEY_ID          FOREIGN KEY (KEY_ID)      REFERENCES KEYS(ID);
ALTER TABLE ACTIVITIES_KEYS ADD CONSTRAINT FK_ACTIVITIES_KEYS__ACTIVITY_ID     FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES(ID);
--ALTER TABLE ACTIVITIES_KEYS ADD CONSTRAINT FK_ACTIVITIES_KEYS__CREATED_BY_ID   FOREIGN KEY (CREATED_BY)  REFERENCES USERS(ID);
--ALTER TABLE ACTIVITIES_KEYS ADD CONSTRAINT FK_ACTIVITIES_KEYS__UPDATED_BY_ID   FOREIGN KEY (UPDATED_BY)  REFERENCES USERS(ID);


CREATE TABLE ACTIVITIES_KEYS_CATEGORIES(
    ID              NUMBER(12) DEFAULT SEQ_ACTIVITIES_KEYS_CATEGORIES.nextval  NOT NULL,
    ACTIVITY_KEY_ID NUMBER(12) NOT NULL, 
	CATEGORY_ID     NUMBER(12) NOT NULL,
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE ACTIVITIES_KEYS_CATEGORIES ADD CONSTRAINT PK_ACTIVITIES_KEYS_CATEGORIES__ID PRIMARY KEY (ID);
ALTER TABLE ACTIVITIES_KEYS_CATEGORIES ADD CONSTRAINT UK_ACTIVITIES_KEYS_CATEGORIES__CATEGORY_ID__ACTIVITY_KEY_ID_UNIQUE UNIQUE (CATEGORY_ID,ACTIVITY_KEY_ID) ENABLE;
ALTER TABLE ACTIVITIES_KEYS_CATEGORIES ADD CONSTRAINT FK_ACTIVITIES_KEYS_CATEGORIES__ACTIVITY_KEY_ID FOREIGN KEY (ACTIVITY_KEY_ID)   REFERENCES ACTIVITIES_KEYS(ID);
ALTER TABLE ACTIVITIES_KEYS_CATEGORIES ADD CONSTRAINT FK_ACTIVITIES_KEYS_CATEGORIES__CATEGORY_ID     FOREIGN KEY (CATEGORY_ID)       REFERENCES CATEGORIES(ID);
--ALTER TABLE ACTIVITIES_KEYS_CATEGORIES ADD CONSTRAINT FK_ACTIVITIES_KEYS_CATEGORIES__CREATED_BY_ID   FOREIGN KEY (CREATED_BY)        REFERENCES USERS(ID);
--ALTER TABLE ACTIVITIES_KEYS_CATEGORIES ADD CONSTRAINT FK_ACTIVITIES_KEYS_CATEGORIES__UPDATED_BY_ID   FOREIGN KEY (UPDATED_BY)        REFERENCES USERS(ID);


CREATE TABLE ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES(
    ID                       NUMBER(12) DEFAULT SEQ_ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES.nextval  NOT NULL,
    ACTIVITY_KEY_CATEGORY_ID NUMBER(12) NOT NULL, 
	SUB_ACTIVITY_ID          NUMBER(12) NOT NULL,
    CREATED_BY               NUMBER(32),
    CREATED_AT               TIMESTAMP(6),
    UPDATED_BY               NUMBER(32),
    UPDATED_AT               TIMESTAMP(6),
    STATE                    NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES ADD CONSTRAINT PK_ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES__ID PRIMARY KEY (ID);
ALTER TABLE ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES ADD CONSTRAINT UK_ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES__SUB_ACTIVITY_ID__ACTIVITY_KEY_CATEGORY_ID_UNIQUE UNIQUE (SUB_ACTIVITY_ID,ACTIVITY_KEY_CATEGORY_ID) ENABLE;
ALTER TABLE ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES ADD CONSTRAINT FK_ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES__ACTIVITY_KEY_CATEGORY_ID  FOREIGN KEY (ACTIVITY_KEY_CATEGORY_ID)  REFERENCES ACTIVITIES_KEYS_CATEGORIES(ID);
ALTER TABLE ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES ADD CONSTRAINT FK_ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES__SUB_ACTIVITY_ID           FOREIGN KEY (SUB_ACTIVITY_ID)           REFERENCES SUB_ACTIVITIES(ID);
--ALTER TABLE ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES ADD CONSTRAINT FK_ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES__CREATED_BY_ID             FOREIGN KEY (CREATED_BY)                REFERENCES USERS(ID);
--ALTER TABLE ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES ADD CONSTRAINT FK_ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES__UPDATED_BY_ID             FOREIGN KEY (UPDATED_BY)                REFERENCES USERS(ID);



CREATE TABLE FORM_PRESENTATION (
    ID                  NUMBER(12) DEFAULT SEQ_FORM_PRESENTATION.nextval NOT NULL,
    NAME                VARCHAR2(200),
    TYPE                VARCHAR2(5),
    DATE_REGISTER       DATE,
    DATE_UNREGISTER     DATE,
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6),
    STATE               NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE FORM_PRESENTATION ADD CONSTRAINT PK_FORM_PRESENTATION__ID PRIMARY KEY (ID);
--ALTER TABLE FORM_PRESENTATION ADD CONSTRAINT FK_FORM_PRESENTATION__CREATED_BY_ID    FOREIGN KEY (CREATED_BY)    REFERENCES USERS(ID);
--ALTER TABLE FORM_PRESENTATION ADD CONSTRAINT FK_FORM_PRESENTATION__UPDATED_BY_ID    FOREIGN KEY (UPDATED_BY)    REFERENCES USERS(ID);


CREATE TABLE RGSEAA
(
    ID                      NUMBER(12) DEFAULT SEQ_RGSEAA.nextval NOT NULL,
    COMPANY_ID              NUMBER(12),
    ESTABLISHMENT_ID        NUMBER(12),
    KEY_ID                  NUMBER(12) NOT NULL,
    NUM_RGSEAA              NUMBER(12),
    ENROLLMENT              VARCHAR2(3),
    DATE_REGISTER           DATE,
    DATE_ANNOTATION         DATE,
    DATE_MODIFICATION       DATE,
    CREATED_BY              NUMBER(12),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(12),
    UPDATED_AT              TIMESTAMP(6),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE RGSEAA ADD CONSTRAINT PK_RGSEAA__ID PRIMARY KEY (ID);
ALTER TABLE RGSEAA ADD CONSTRAINT FK_RGSEAA__COMPANY_ID         FOREIGN KEY (COMPANY_ID)        REFERENCES COMPANIES(ID);
ALTER TABLE RGSEAA ADD CONSTRAINT FK_RGSEAA__ESTABLISHMENT_ID   FOREIGN KEY (ESTABLISHMENT_ID)  REFERENCES ESTABLISHMENTS(ID);
ALTER TABLE RGSEAA ADD CONSTRAINT FK_RGSEAA__KEY_ID             FOREIGN KEY (KEY_ID)            REFERENCES KEYS(ID);
--ALTER TABLE RGSEAA ADD CONSTRAINT FK_RGSEAA__CREATED_BY_ID      FOREIGN KEY (CREATED_BY)        REFERENCES USERS(ID);
--ALTER TABLE RGSEAA ADD CONSTRAINT FK_RGSEAA__UPDATED_BY_ID      FOREIGN KEY (UPDATED_BY)        REFERENCES USERS(ID);
-- COMPANY, ESTABLISHMENT y KEY deberían ser unicas?

--Pendiente revisar en Backend por problemas con la vista asociada
CREATE TABLE RGSEAA_ACTIVITIES_PENDIENTE_REVISAR_EN_BACKEND
(
    ID                                      NUMBER(12) DEFAULT SEQ_RGSEAA_ACTIVITIES.nextval NOT NULL,
    RGSEAA_ID                               NUMBER(12) NOT NULL,
    ACTIVITY_KEY_CATEGORY_SUB_ACTIVITY_ID   NUMBER(12) NOT NULL,
    CREATED_BY                              NUMBER(12),
    CREATED_AT                              TIMESTAMP(6),
    UPDATED_BY                              NUMBER(12),
    UPDATED_AT                              TIMESTAMP(6),
    STATE                                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE RGSEAA_ACTIVITIES_PENDIENTE_REVISAR_EN_BACKEND ADD CONSTRAINT PK_RGSEAA_ACTIVITIES_PENDIENTE_REVISAR_EN_BACKEND__ID PRIMARY KEY (ID);
ALTER TABLE RGSEAA_ACTIVITIES_PENDIENTE_REVISAR_EN_BACKEND ADD CONSTRAINT FK_RGSEAA_ACTIVITIES_PENDIENTE_REVISAR_EN_BACKEND__ACTIVITY_KEY_CATEGORY_SUB_ACTIVITY_ID    FOREIGN KEY (ACTIVITY_KEY_CATEGORY_SUB_ACTIVITY_ID)     REFERENCES ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES(ID);
ALTER TABLE RGSEAA_ACTIVITIES_PENDIENTE_REVISAR_EN_BACKEND ADD CONSTRAINT FK_RGSEAA_ACTIVITIES_PENDIENTE_REVISAR_EN_BACKEND__RGSEAA_ID                                FOREIGN KEY (RGSEAA_ID)                                 REFERENCES RGSEAA(ID);
--ALTER TABLE RGSEAA_ACTIVITIES ADD CONSTRAINT FK_RGSEAA_ACTIVITIES__CREATED_BY_ID    FOREIGN KEY (CREATED_BY)        REFERENCES USERS(ID);
--ALTER TABLE RGSEAA_ACTIVITIES ADD CONSTRAINT FK_RGSEAA_ACTIVITIES__UPDATED_BY_ID    FOREIGN KEY (UPDATED_BY)        REFERENCES USERS(ID);

CREATE TABLE RGSEAA_ACTIVITIES
(
    ID                                      NUMBER(12) DEFAULT SEQ_RGSEAA_ACTIVITIES.nextval NOT NULL,
    RGSEAA_ID                               NUMBER(12) NOT NULL,
    ACTIVITY_ID                             NUMBER(12) NOT NULL,
    CATEGORY_ID                             NUMBER(12) NOT NULL,
    SUB_ACTIVITY_ID                         NUMBER(12) NOT NULL,
    CREATED_BY                              NUMBER(12),
    CREATED_AT                              TIMESTAMP(6),
    UPDATED_BY                              NUMBER(12),
    UPDATED_AT                              TIMESTAMP(6),
    STATE                                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE RGSEAA_ACTIVITIES ADD CONSTRAINT PK_RGSEAA_ACTIVITIES__ID PRIMARY KEY (ID);
ALTER TABLE RGSEAA_ACTIVITIES ADD CONSTRAINT FK_RGSEAA_ACTIVITIES__RGSEAA_ID      FOREIGN KEY (RGSEAA_ID)       REFERENCES RGSEAA(ID);
ALTER TABLE RGSEAA_ACTIVITIES ADD CONSTRAINT FK_RGSEAA_ACTIVITIES__ACTIVITY_ID    FOREIGN KEY (ACTIVITY_ID)     REFERENCES ACTIVITIES(ID);
ALTER TABLE RGSEAA_ACTIVITIES ADD CONSTRAINT FK_RGSEAA_ACTIVITIES__CATEGORY_ID    FOREIGN KEY (CATEGORY_ID)     REFERENCES CATEGORIES(ID);
ALTER TABLE RGSEAA_ACTIVITIES ADD CONSTRAINT FK_RGSEAA_ACTIVITIES__SUB_ACTIVITY_ID    FOREIGN KEY (SUB_ACTIVITY_ID)     REFERENCES SUB_ACTIVITIES(ID);
--ALTER TABLE RGSEAA_ACTIVITIES ADD CONSTRAINT FK_RGSEAA_ACTIVITIES__CREATED_BY_ID    FOREIGN KEY (CREATED_BY)        REFERENCES USERS(ID);
--ALTER TABLE RGSEAA_ACTIVITIES ADD CONSTRAINT FK_RGSEAA_ACTIVITIES__UPDATED_BY_ID    FOREIGN KEY (UPDATED_BY)        REFERENCES USERS(ID);


CREATE TABLE FEES
(
    ID                      NUMBER(12) DEFAULT SEQ_FEES.nextval NOT NULL,
    NAME                    VARCHAR2(100),
    DESCRIPTION             VARCHAR2(200),
    AMOUNT                  NUMBER(12),
    CREATED_BY              NUMBER(12),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(12),
    UPDATED_AT              TIMESTAMP(6),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE FEES ADD CONSTRAINT PK_FEES__ID PRIMARY KEY (ID);
--ALTER TABLE RGSEAA ADD CONSTRAINT FK_RGSEAA__CREATED_BY_ID    FOREIGN KEY (CREATED_BY)       REFERENCES USERS(ID);
--ALTER TABLE RGSEAA ADD CONSTRAINT FK_RGSEAA__UPDATED_BY_ID    FOREIGN KEY (UPDATED_BY)       REFERENCES USERS(ID);

CREATE TABLE RGSEAA_FEES
(
    ID                      NUMBER(12) DEFAULT SEQ_RGSEAA_FEES.nextval NOT NULL,
    RGSEAA_ID               NUMBER(12) NOT NULL,
    FEE_ID                  NUMBER(12) NOT NULL,
    CREATED_BY              NUMBER(12),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(12),
    UPDATED_AT              TIMESTAMP(6),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE RGSEAA_FEES ADD CONSTRAINT PK_RGSEAA_FEES__ID PRIMARY KEY (ID);
ALTER TABLE RGSEAA_FEES ADD CONSTRAINT FK_RGSEAA_FEES__RGSEAA_ID    FOREIGN KEY (RGSEAA_ID)     REFERENCES RGSEAA(ID);
ALTER TABLE RGSEAA_FEES ADD CONSTRAINT FK_RGSEAA_FEES__FEE_ID       FOREIGN KEY (FEE_ID)        REFERENCES FEES(ID);
--ALTER TABLE RGSEAA ADD CONSTRAINT FK_RGSEAA__CREATED_BY_ID    FOREIGN KEY (CREATED_BY)       REFERENCES USERS(ID);
--ALTER TABLE RGSEAA ADD CONSTRAINT FK_RGSEAA__UPDATED_BY_ID    FOREIGN KEY (UPDATED_BY)       REFERENCES USERS(ID);


CREATE TABLE RGSEAA_AUTHORIZATIONS
(
    ID                      NUMBER(12) DEFAULT SEQ_RGSEAA_AUTHORIZATIONS.nextval NOT NULL,
    AUTHORIZATION_ID        NUMBER(12) NOT NULL,
    RGSEAA_ID               NUMBER(12) NOT NULL,
    CREATED_BY              NUMBER(12),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(12),
    UPDATED_AT              TIMESTAMP(6),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE RGSEAA_AUTHORIZATIONS ADD CONSTRAINT RGSEAA_AUTHORIZATIONS__ID PRIMARY KEY (ID);
ALTER TABLE RGSEAA_AUTHORIZATIONS ADD CONSTRAINT RGSEAA_AUTHORIZATIONS__AUTHORIZATION_ID    FOREIGN KEY(AUTHORIZATION_ID)   REFERENCES AUTHORIZATIONS(ID);
ALTER TABLE RGSEAA_AUTHORIZATIONS ADD CONSTRAINT RGSEAA_AUTHORIZATIONS__RGSEAA_ID           FOREIGN KEY(RGSEAA_ID)          REFERENCES RGSEAA(ID);


CREATE TABLE SUBSTANCES
(
    ID                      NUMBER(12) DEFAULT SEQ_SUBSTANCES.nextval NOT NULL,
    NAME                    VARCHAR(200) NOT NULL,
    CREATED_BY              NUMBER(12),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(12),
    UPDATED_AT              TIMESTAMP(6),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE SUBSTANCES ADD CONSTRAINT SUBSTANCES__ID PRIMARY KEY (ID);


-- - - - - - - - - VIEWS - - - - - - - - - 

CREATE OR REPLACE FORCE EDITIONABLE VIEW VIEW_RGSEAA_KEYS_ACTIVITIES_CATEGORIES_SUB_ACTIVITIES (
"RGSEAA_ID", "NUM_RGSEAA", "KEY_ID", "KEY_NAME", "ACTIVITY_ID", "ACTIVITY_NAME", "CATEGORY_ID", "CATEGORY_NAME", "SUB_ACTIVITY_ID", "SUB_ACTIVITY_NAME") DEFAULT COLLATION "BINARY_AI"  AS 
  SELECT R.ID AS RGSEAA_ID,
  R.NUM_RGSEAA AS NUM_RGSEAA, 
  K.ID AS KEY_ID,
  K.NAME AS KEY_NAME,
  A.ID AS ACTIVITY_ID,
  A.NAME AS ACTIVITY_NAME,
  C.ID AS CATEGORY_ID,
  C.NAME AS CATEGORY_NAME,
  SA.ID AS SUB_ACTIVITY_ID,
  SA.NAME AS SUB_ACTIVITY_NAME
FROM RGSEAA R
  JOIN RGSEAA_ACTIVITIES_PENDIENTE_REVISAR_EN_BACKEND RA ON R.ID = RA.RGSEAA_ID
  RIGHT JOIN ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES AKCSA ON AKCSA.ID = RA.ACTIVITY_KEY_CATEGORY_SUB_ACTIVITY_ID
  JOIN SUB_ACTIVITIES SA ON AKCSA.SUB_ACTIVITY_ID = SA.ID
  JOIN ACTIVITIES_KEYS_CATEGORIES AKC ON AKC.ID = AKCSA.ACTIVITY_KEY_CATEGORY_ID
  JOIN CATEGORIES C ON C.ID = AKC.CATEGORY_ID
  JOIN ACTIVITIES_KEYS AK ON AKC.ACTIVITY_KEY_ID = AK.ID
  JOIN ACTIVITIES A ON AK.ACTIVITY_ID = A.ID
  JOIN KEYS K ON AK.KEY_ID = K.ID;
