
CREATE SEQUENCE SEQ_ACTIONS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_AUTHORIZATIONS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_DOCUMENTS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_ENTITIES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_ENTITIES_TYPES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_INDUSTRIES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_INDUSTRIES_AUTHORIZATIONS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_MODULES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_MODULES_TYPES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_PERMISSIONS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_PRODUCTS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_PROFILES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_PROFILES_PERMISSIONS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_USERS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_USERS_MODELS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_USERS_PROFILES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_ACTIVITIES START WITH 600 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_INDUSTRIES_KEYS_ACTIVITIES_CATEGORIES START WITH 10000 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_TYPE_EXPEDIENTS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_TYPE_CHANGE_EXPEDIENTS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_EXPEDIENTS START WITH 10000 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_TYPE_SUBSTANCES START WITH 100 INCREMENT BY 1 CACHE 30;

CREATE TABLE ENTITIES_TYPES
(
    ID              NUMBER(12) NOT NULL,
    DESCRIPTION     VARCHAR2(255 char),
    NAME            VARCHAR2(255 char) NOT NULL,
    ID_STATE        NUMBER(12) DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP(6),
    CREATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32)
);
ALTER TABLE ENTITIES_TYPES ADD CONSTRAINT PK_ENTITIES_TYPES__ID PRIMARY KEY (ID);


CREATE TABLE ENTITIES
(
    ID              NUMBER(12) NOT NULL,
    NAME            VARCHAR2(100 char) NOT NULL,
    DESCRIPTION     VARCHAR2(100 char) NOT NULL,
    CODE            VARCHAR2(6 char) NOT NULL,
    ID_TYPE         NUMBER(32)  NOT NULL,
    ADDRESS         VARCHAR2(255 char),
    CONTACT_PERSON  VARCHAR2(255 char),
    EMAIL           VARCHAR2(255 char),
    PHONE           VARCHAR2(255 char),
    POSTAL_CODE     VARCHAR2(255 char),
    ROOT_ENTITY     NUMBER(1),
    ID_STATE        NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP(6)     not null,
    CREATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6)     not null,
    UPDATED_BY      NUMBER(32)
);
ALTER TABLE ENTITIES ADD CONSTRAINT PK_ENTITIES__ID PRIMARY KEY (ID);
ALTER TABLE ENTITIES ADD CONSTRAINT UK_ENTITIES__CODE UNIQUE (CODE);
ALTER TABLE ENTITIES ADD CONSTRAINT FK_ENTITIES__ID_TYPE FOREIGN KEY (ID_TYPE) REFERENCES ENTITIES_TYPES(ID);



CREATE TABLE LANGUAGES
(
    ID          NUMBER(12) GENERATED AS IDENTITY NOT NULL,
    ID_STATE    NUMBER(10) DEFAULT 1 NOT NULL,
    COD_ISO_639 VARCHAR2(4 char) not null,
    NAME        VARCHAR2(256 char)
);
ALTER TABLE LANGUAGES ADD CONSTRAINT PK_LANGUAGES__ID PRIMARY KEY (ID);



CREATE TABLE MODULES_TYPES
(
    ID         NUMBER(12) NOT NULL,
    ID_STATE   NUMBER(12) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6),
    CREATED_BY NUMBER(32),
    UPDATED_AT TIMESTAMP(6),
    UPDATED_BY NUMBER(32)
);
ALTER TABLE MODULES_TYPES ADD CONSTRAINT PK_MODULES_TYPES__ID PRIMARY KEY (ID);



CREATE TABLE MODULES
(
    ID         NUMBER(12) NOT NULL,
    CODE       VARCHAR2(6 char) NOT NULL,
    ID_TYPE    NUMBER(12),
    ID_STATE   NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6),
    CREATED_BY NUMBER(32),
    UPDATED_AT TIMESTAMP(6),
    UPDATED_BY NUMBER(32)
);
ALTER TABLE MODULES ADD CONSTRAINT PK_MODULES__ID PRIMARY KEY (ID);
ALTER TABLE MODULES ADD CONSTRAINT UK_MODULES__CODE UNIQUE (CODE);
ALTER TABLE MODULES ADD CONSTRAINT FK_MODULES__ID_TYPE FOREIGN KEY (ID_TYPE) REFERENCES MODULES_TYPES(ID);



CREATE TABLE MODULES_LANGUAGES
(
    ID          NUMBER(12) NOT NULL,
    ID_LANGUAGE NUMBER(12)  NOT NULL,
    DESCRIPTION VARCHAR2(500 char),
    NAME        VARCHAR2(100 char) NOT NULL,
    ID_STATE    NUMBER(10) DEFAULT 1 NOT NULL
);
ALTER TABLE MODULES_LANGUAGES ADD CONSTRAINT PK_MODULES_LANGUAGES__ID PRIMARY KEY (ID,ID_LANGUAGE);
ALTER TABLE MODULES_LANGUAGES ADD CONSTRAINT FK_MODULES_LANGUAGES__ID FOREIGN KEY (ID) REFERENCES MODULES_TYPES(ID);
ALTER TABLE MODULES_LANGUAGES ADD CONSTRAINT FK_MODULES_LANGUAGES__ID_LANGUAGE FOREIGN KEY (ID_LANGUAGE) REFERENCES LANGUAGES(ID);



CREATE TABLE MODULES_TYPES_LANGUAGES
(
    ID          NUMBER(12)  NOT NULL,
    ID_LANGUAGE NUMBER(12)  NOT NULL,
    DESCRIPTION VARCHAR2(500 char),
    NAME        VARCHAR2(100 char) NOT NULL,
    ID_STATE    NUMBER(10) DEFAULT 1 NOT NULL
);
ALTER TABLE MODULES_TYPES_LANGUAGES ADD CONSTRAINT PK_MODULES_TYPES_LANGUAGES__ID PRIMARY KEY (ID,ID_LANGUAGE);
ALTER TABLE MODULES_TYPES_LANGUAGES ADD CONSTRAINT FK_MODULES_TYPES_LANGUAGES__ID FOREIGN KEY (ID) REFERENCES MODULES_TYPES(ID);
ALTER TABLE MODULES_TYPES_LANGUAGES ADD CONSTRAINT FK_MODULES_TYPES_LANGUAGES__ID_LANGUAGE FOREIGN KEY (ID_LANGUAGE) REFERENCES LANGUAGES(ID);



CREATE TABLE PERMISSIONS
(
    ID         NUMBER(12) NOT NULL,
    ID_STATE   NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6),
    CREATED_BY NUMBER(32),
    UPDATED_AT TIMESTAMP(6),
    UPDATED_BY NUMBER(32),
    CODE       VARCHAR2(100 char)
);
ALTER TABLE PERMISSIONS ADD CONSTRAINT PK_PERMISSIONS__ID PRIMARY KEY (ID);



CREATE TABLE PERMISSIONS_LANGUAGE
(
    ID          NUMBER(12) NOT NULL,
    ID_LANGUAGE NUMBER(12) NOT NULL,
    DESCRIPTION VARCHAR2(100 char),
    NAME        VARCHAR2(20 char) NOT NULL
);
ALTER TABLE PERMISSIONS_LANGUAGE ADD CONSTRAINT PK_PERMISSIONS_LANGUAGE__ID PRIMARY KEY (ID,ID_LANGUAGE);
ALTER TABLE PERMISSIONS_LANGUAGE ADD CONSTRAINT FK_PERMISSIONS_LANGUAGE__ID FOREIGN KEY (ID) REFERENCES PERMISSIONS(ID);
ALTER TABLE PERMISSIONS_LANGUAGE ADD CONSTRAINT FK_PERMISSIONS_LANGUAGE__ID_LANGUAGE FOREIGN KEY (ID_LANGUAGE) REFERENCES LANGUAGES(ID);



CREATE TABLE PROFILES
(
    ID         NUMBER(12) NOT NULL,
    NAME       VARCHAR2(255 char) NOT NULL,
    ID_STATE   NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6),
    CREATED_BY NUMBER(32),
    UPDATED_AT TIMESTAMP(6),
    UPDATED_BY NUMBER(32)
);
ALTER TABLE PROFILES ADD CONSTRAINT PK_PROFILES__ID PRIMARY KEY (ID);



CREATE TABLE PROFILES_PERMISSIONS
(
    ID            NUMBER(12) NOT NULL,
    ID_PERMISSION NUMBER(32) NOT NULL,
    ID_PROFILE    NUMBER(32) NOT NULL,
    ID_STATE      NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_AT    TIMESTAMP(6) not null,
    CREATED_BY    NUMBER(32),
    UPDATED_AT    TIMESTAMP(6) not null,
    UPDATED_BY    NUMBER(32)
);
ALTER TABLE PROFILES_PERMISSIONS ADD CONSTRAINT PK_PROFILES_PERMISSIONS__ID PRIMARY KEY (ID);
ALTER TABLE PROFILES_PERMISSIONS ADD CONSTRAINT FK_PROFILES_PERMISSIONS__ID_PERMISSION FOREIGN KEY (ID_PERMISSION) REFERENCES PERMISSIONS(ID);
ALTER TABLE PROFILES_PERMISSIONS ADD CONSTRAINT FK_PROFILES_PERMISSIONS__ID_PROFILE FOREIGN KEY (ID_PROFILE) REFERENCES PROFILES(ID);



CREATE TABLE USERS
(
    ID             NUMBER(12) NOT NULL,
    EMAIL          VARCHAR2(255 char),
    FIRST_SURNAME  VARCHAR2(255 char),
    NAME           VARCHAR2(255 char),
    NIF            VARCHAR2(9 char),
    PHONE          VARCHAR2(255 char),
    SECOND_SURNAME VARCHAR2(255 char),
    ID_STATE       NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT     TIMESTAMP(6),
    CREATED_BY     NUMBER(32),
    UPDATED_AT     TIMESTAMP(6),
    UPDATED_BY     NUMBER(32)
);
ALTER TABLE USERS ADD CONSTRAINT PK_USERS__ID PRIMARY KEY (ID);
ALTER TABLE USERS ADD CONSTRAINT UK_USERS__NIF UNIQUE (NIF);



CREATE TABLE USERS_ENTITIES
(
    ID_ENTITY  NUMBER(12)  NOT NULL,
    ID_USER    NUMBER(12)  NOT NULL,
    ID_STATE   NUMBER(1) DEFAULT 1 NOT NULL,
    SCOPE_CODE VARCHAR2(20 char) NOT NULL
);
ALTER TABLE USERS_ENTITIES ADD CONSTRAINT PK_USERS_ENTITIES PRIMARY KEY (ID_ENTITY,ID_USER);
ALTER TABLE USERS_ENTITIES ADD CONSTRAINT FK_USERS_ENTITIES__ID_ENTITY FOREIGN KEY (ID_ENTITY) REFERENCES ENTITIES(ID);
ALTER TABLE USERS_ENTITIES ADD CONSTRAINT FK_USERS_ENTITIES__ID_USER FOREIGN KEY (ID_USER) REFERENCES USERS(ID);



CREATE TABLE USERS_MODELS
(
    ID         NUMBER(32)  NOT NULL,
    ID_MODULE  NUMBER(12),
    ID_USER    NUMBER(12),
    ID_STATE   NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6),
    CREATED_BY NUMBER(32),
    UPDATED_AT TIMESTAMP(6),
    UPDATED_BY NUMBER(32)
);
ALTER TABLE USERS_MODELS ADD CONSTRAINT PK_USERS_MODELS_ID PRIMARY KEY (ID);
ALTER TABLE USERS_MODELS ADD CONSTRAINT FK_USERS_MODELS__ID_MODULE FOREIGN KEY (ID_MODULE) REFERENCES MODULES(ID);
ALTER TABLE USERS_MODELS ADD CONSTRAINT FK_USERS_MODELS__ID_USER FOREIGN KEY (ID_USER) REFERENCES USERS(ID);



CREATE TABLE USERS_PROFILES
(
    ID          NUMBER(12) NOT NULL,
    ID_PROFILE  NUMBER(12),
    ID_USER     NUMBER(12),
    ID_STATE    NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT  TIMESTAMP(6) NOT NULL,
    CREATED_BY  NUMBER(32),
    UPDATED_AT  TIMESTAMP(6),
    UPDATED_BY  NUMBER(12)
);
ALTER TABLE USERS_PROFILES ADD CONSTRAINT PK_USERS_PROFILES_ID PRIMARY KEY (ID);
ALTER TABLE USERS_PROFILES ADD CONSTRAINT FK_USERS_PROFILES__ID_PROFILE FOREIGN KEY (ID_PROFILE) REFERENCES PROFILES(ID);
ALTER TABLE USERS_PROFILES ADD CONSTRAINT FK_USERS_PROFILES__ID_USER FOREIGN KEY (ID_USER) REFERENCES USERS(ID);



CREATE TABLE AUTH_USER_REQUEST
(
    PETITION_ID        VARCHAR2(36)   NOT NULL,
    RELAY_ID           VARCHAR2(20)   NOT NULL,
    TOKEN              VARCHAR2(4000) NOT NULL,
    EXP                NUMBER(38)     NOT NULL,
    PROCESS_RETURN_URL VARCHAR2(4000) NOT NULL
);
ALTER TABLE AUTH_USER_REQUEST ADD CONSTRAINT PK_AUTH_USER_REQUEST__PETITION_ID PRIMARY KEY (PETITION_ID);
ALTER TABLE AUTH_USER_REQUEST ADD CONSTRAINT PK_AUTH_USER_REQUEST__RELAY_ID UNIQUE (RELAY_ID);



CREATE TABLE AUTH_USER_TOKEN
(
    PETITION_ID VARCHAR2(36)   NOT NULL,
    RELAY_ID    VARCHAR2(20)   NOT NULL,
    DOC_NUM     VARCHAR2(50)   NOT NULL,
    TOKEN       VARCHAR2(4000) NOT NULL,
    EXP         NUMBER(38)     NOT NULL
);
ALTER TABLE AUTH_USER_TOKEN ADD CONSTRAINT PK_AUTH_USER_TOKEN__PETITION_ID PRIMARY KEY (PETITION_ID);
ALTER TABLE AUTH_USER_TOKEN ADD CONSTRAINT UK_AUTH_USER_TOKEN__RELAY_ID UNIQUE (RELAY_ID);



CREATE TABLE KEYS (
    ID                  NUMBER(12) NOT NULL,
    NAME                VARCHAR2(200),
    DATE_REGISTER       DATE,
    DATE_UNREGISTER     DATE,
    ALLOW_PRODUCT       NUMBER,
    IS_OLD              NUMBER DEFAULT 0,
    IS_PUBLIC           NUMBER DEFAULT 1,
    ID_STATE            NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6)
);
COMMENT ON TABLE KEYS IS 'Migrada de TBRGSA_CLAVE';
ALTER TABLE KEYS ADD CONSTRAINT PK_CLAVE__ID PRIMARY KEY (ID);


CREATE TABLE DENOMINATION_SALES (
    ID              NUMBER(12) NOT NULL,
    NAME            VARCHAR2(200),
    ID_KEY          NUMBER(12),
    FILE_TYPE       VARCHAR2(5),
    ID_ACTIVITY     VARCHAR2(4),
    IS_PUBLIC       NUMBER(1) DEFAULT 0,
    DATE_REGISTER   DATE,
    DATE_UNREGISTER DATE,
    ACTIVE          NUMBER(1) DEFAULT 1,
    ID_STATE        NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6)
);
COMMENT ON TABLE DENOMINATION_SALES IS 'Migrada de TBRGSA_DENOMINACIONVENTA';
ALTER TABLE DENOMINATION_SALES ADD CONSTRAINT PK_DENOMINATION_SALES__ID PRIMARY KEY (ID);




CREATE TABLE SITUATIONS (
    ID                      NUMBER(12) NOT NULL,
    NAME                    VARCHAR2(50),
    TYPE_INDUSTRY_PRODUCT   NUMBER,
    NEW_OPTION              NUMBER,
    NO_DELETE               NUMBER DEFAULT 0,
    VISIBLE_RGSA            NUMBER DEFAULT 1,
    VISIBLE_UE              NUMBER DEFAULT 1,
    ID_STATE                NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_BY              NUMBER(32),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6)
);
COMMENT ON TABLE SITUATION IS 'Migrada de TBRGSA_SITUACION';
ALTER TABLE SITUATION ADD CONSTRAINT PK_SITUATION__ID PRIMARY KEY (ID);



CREATE TABLE COUNTRIES (
    ID                  NUMBER(32) NOT NULL,
    NAME                VARCHAR2(50),
    ENROLLMENT          VARCHAR2(3),
    NO_DELETE           NUMBER,
    ID_STATE            NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6)
);
COMMENT ON TABLE COUNTRIES IS 'Migrada de TBRGSA_PAISES';
ALTER TABLE COUNTRIES ADD CONSTRAINT PK_COUNTRIES__ID PRIMARY KEY (ID);



CREATE TABLE FORM_PRESENTATION (
    ID                  NUMBER(12) NOT NULL,
    NAME                VARCHAR2(200),
    TYPE                VARCHAR2(5),
    DATE_REGISTER       DATE,
    DATE_UNREGISTER     DATE,
    ID_STATE            NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6)
);
COMMENT ON TABLE FORM_PRESENTATION IS 'Migrada de TBRGSA_FORMAPRESENTACION';
ALTER TABLE FORM_PRESENTATION ADD CONSTRAINT PK_FORM_PRESENTATION__ID PRIMARY KEY (ID);



create table STATES (
    ID              NUMBER(12) NOT NULL,
    CODE            VARCHAR2(30),
    NAME            VARCHAR2(30),
    ID_STATE        NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6)
);
ALTER TABLE STATES ADD CONSTRAINT PK_STATES__ID PRIMARY KEY (ID);


CREATE TABLE INDUSTRIES
(
    ID                      NUMBER(12) NOT NULL,
    ID_KEY                  NUMBER(12),
    DATE_REGISTER           DATE,
    DATE_UNREGISTER         DATE,
    NAME_BUSINESS           VARCHAR2(200),
    DATE_INSCRIPTION        DATE,
    ENROLLMENT              VARCHAR2(3),
    NUMBER_INDUSTRY         VARCHAR2(6),
    ADDRESS_BUSINESS        VARCHAR2(500),
    LOCATION_BUSINESS       VARCHAR2(200),
    POSTAL_CODE_BUSINESS    VARCHAR2(20),
    ADDRESS_INDUSTRY        VARCHAR2(500),
    LOCATION_INDUSTRY       VARCHAR2(200),
    POSTAL_CODE_INDUSTRY   VARCHAR2(20),
    CIF                     VARCHAR2(20),
    DATE_VALIDATION         DATE,
    DATE_LAST_UPDATE        DATE,
    OBSERVATION             VARCHAR2(2000),
    ID_SITUATION            NUMBER(12),
    PROVINCE_INDUSTRY       VARCHAR2(3),
    PROVINCE_BUSINESS       VARCHAR2(3),
    ID_COUNTRY_BUSINESS     NUMBER(12),
    ID_COUNTRY_INDUSTRY     NUMBER(12),
    ID_USER                 NUMBER(12),
    NUM_REG_CCAA            VARCHAR2(15),
    REGISTERED              NUMBER(1),
    ID_STATE_INDUSTRY       NVARCHAR2(5),
    ADDRESS_INSTALLATION    VARCHAR2(2000),
    CCAA_USER_ADD           VARCHAR2(5),
    EMAIL                   VARCHAR2(200),
    NUM_BUSINESS            NUMBER,
    MIGRATION               VARCHAR2(4000),
    UPDATE_REGISTER         NUMBER    DEFAULT 0,
    NUM_REGISTER            VARCHAR2(25),
    ID_ENTITY               NUMBER(12),
    LOCATION_PREVIOUS       NVARCHAR2(500),
    FOLDER_MIGRATION        VARCHAR2(10),
    DATE_REQUEST            DATE,
    NAME_BUSINESS_FORMAT    VARCHAR2(200),
    ADDRESS_INDUSTRY_FORMAT VARCHAR2(500),
    MTPIENSOS               NUMBER(1) DEFAULT 0,
    PAGE_WEB                VARCHAR2(2000),
    ID_STATE                NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_BY              NUMBER(32),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6)
);
ALTER TABLE INDUSTRIES ADD CONSTRAINT PK_INDUSTRIES__ID PRIMARY KEY (ID);
ALTER TABLE INDUSTRIES ADD CONSTRAINT FK_INDUSTRIES__ID_KEY FOREIGN KEY (ID_KEY) REFERENCES KEYS(ID);
ALTER TABLE INDUSTRIES ADD CONSTRAINT FK_INDUSTRIES__ID_COUNTRY_BUSINESS FOREIGN KEY (ID_COUNTRY_BUSINESS) REFERENCES COUNTRIES(ID);
ALTER TABLE INDUSTRIES ADD CONSTRAINT FK_INDUSTRIES__ID_COUNTRY_INDUSTRY FOREIGN KEY (ID_COUNTRY_INDUSTRY) REFERENCES COUNTRIES(ID);
ALTER TABLE INDUSTRIES ADD CONSTRAINT FK_INDUSTRIES__ID_USER FOREIGN KEY (ID_USER) REFERENCES USERS(ID);
ALTER TABLE INDUSTRIES ADD CONSTRAINT FK_INDUSTRIES__ID_ENTITY FOREIGN KEY (ID_ENTITY) REFERENCES ENTITIES(ID);



CREATE TABLE PRODUCTS (
    ID                          NUMBER(12),
    CREATED_AT                  DATE,
    ID_DENOMINATION_SALE        NUMBER(12),
    OBSERVATION                 VARCHAR2(500),
    ID_INDUSTRY                 NUMBER(12),
    BRAND                       VARCHAR2(200),
    NUM_REG_CCAA                VARCHAR2(25),
    ID_SITUATION                NUMBER(12),
    CREATED_BY                  NUMBER(32),
    REGISTERED                  NUMBER(1),
    ID_STATE_PRODUCT            NUMBER(12),
    NUM_PRODUCT                 VARCHAR2(10),
    ID_KEY                      NUMBER(12),
    SOURCE                      VARCHAR2(200),
    PLACE_LOCATION              VARCHAR2(200),
    REGISTRATION_KEY_27         VARCHAR2(3),
    DESC_COUNTRY_LOCATION       VARCHAR2(200),
    COUNTRY_LOCATION            NUMBER(1),
    ID_COUNTRY_MANUFACTURING    NUMBER(12),
    ID_COUNTRY_MARKETING        NUMBER(12),
    OTHER_COUNTRIES             VARCHAR2(200),
    INDUSTRY_ADDRESS            VARCHAR2(710),
    INGREDIENTS                 VARCHAR2(2000),
    ID_FORM_PRESENTATION        NUMBER(12),
    CCAA_USER_CREATOR           VARCHAR2(5),
    ENROLLMENT                  VARCHAR2(3),
    INDUSTRY_NUM                VARCHAR2(6),
    INDUSTRY_NAME               VARCHAR2(200),
    TYPE_PACKAGING              VARCHAR2(200),
    SOCIAL_REASON_KEY_26        VARCHAR2(200),
    PRODUCT_NAME_IA_KEY_26      VARCHAR2(200),
    ID_COUNTRY_IA_KEY_26        NUMBER(12),
    ADDRESS_IA_CODE_26          VARCHAR2(200),
    INDUSTRY_EMAIL              VARCHAR2(200),
    INDUSTRY_PHONE              VARCHAR2(20),
    SUBSTANCE_TYPE              NUMBER,
    EMAIL_CODE_26               VARCHAR2(200),
    PHONE_IA_CODE_26            VARCHAR2(20),
    CREATED_AT_NOT              DATE,
    DATE_TERMINATION            DATE,
    DATE_DENIAL                 DATE,
    PRODUCT_TYPE                VARCHAR2(5),
    DATE_REGISTER_27            DATE,
    DATE_UNREGISTER_27          DATE,
    DATE_TERMINATION_27         DATE,
    ID_COMPETENT_AUTHORITY      NUMBER(12),
    OTHER_COUNTRIES_COMER       VARCHAR2(200),
    OTHER_FORMS                 VARCHAR2(200),
    MIGRATION                   VARCHAR2(4000),
    COUNTER                     VARCHAR2(1),
    DATE_LAST_ACTUATION         DATE,
    MIGRATION_FOLDER            VARCHAR2(10),
    NAME_EXCEL                  VARCHAR2(200),
    DATE_APPLICATION            DATE,
    FORMATTED_MARK              VARCHAR2(200),
    ID_SITUATION_OLD            NUMBER(12),
    ID_COUNTRY_COMPANY_RESP     NUMBER(12),
    OTHER_COUNTRY_COMPANY_RESP  VARCHAR2(200),
    ID_COUNTRY_NOTIFICATION     NUMBER(12),
    OTHER_COUNTRY_NOTIFICATION  VARCHAR2(200),
    WEB_PAGE                    VARCHAR2(2000),
    UPDATED_BY                  NUMBER(32),
    UPDATED_AT                  TIMESTAMP(6),
    ID_STATE                    NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE PRODUCTS ADD CONSTRAINT PK_PRODUCTS__ID PRIMARY KEY (ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS__ID_DENOMINATION_SALES FOREIGN KEY (ID_DENOMINATION_SALE) REFERENCES DENOMINATION_SALES(ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS__ID_INDUSTRY FOREIGN KEY (ID_INDUSTRY) REFERENCES INDUSTRIES(ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS__ID_SITUATION FOREIGN KEY (ID_SITUATION) REFERENCES SITUATION(ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS__ID_KEY FOREIGN KEY (ID_KEY) REFERENCES KEYS(ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS__ID_COUNTRY_MANUFACTURING FOREIGN KEY (ID_COUNTRY_MANUFACTURING) REFERENCES COUNTRIES(ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS__ID_COUNTRY_MARKETING FOREIGN KEY (ID_COUNTRY_MARKETING) REFERENCES COUNTRIES(ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS__ID_COUNTRY_IA_KEY_26 FOREIGN KEY (ID_COUNTRY_IA_KEY_26) REFERENCES KEYS(ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS__ID_COMPETENT_AUTHORITY FOREIGN KEY (ID_COMPETENT_AUTHORITY) REFERENCES ENTITIES(ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS__ID_SITUATION_OLD FOREIGN KEY (ID_SITUATION_OLD) REFERENCES SITUATION(ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS__ID_COUNTRY_COMPANY_RESP FOREIGN KEY (ID_COUNTRY_COMPANY_RESP) REFERENCES COUNTRIES(ID);
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS__ID_COUNTRY_NOTIFICATION FOREIGN KEY (ID_COUNTRY_NOTIFICATION) REFERENCES COUNTRIES(ID);


CREATE TABLE CATEGORIES (
    ID              NUMBER(12) NOT NULL,
    NAME            VARCHAR2(200),
    ID_STATE        NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6)
);
ALTER TABLE CATEGORIES ADD CONSTRAINT PK_CATEGORIES__ID PRIMARY KEY (ID);


CREATE TABLE TYPES_ACTIONS
(
    ID                      NUMBER(12) NOT NULL,
    NAME                    VARCHAR2(250),
    ID_TYPE_COMPANY_PRODUCT NUMBER(12),
    VISIBLE_CCAA            NUMBER,
    NO_DELETE               NUMBER,
    ID_STATE                NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_BY              NUMBER(32),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6),
    STATUS                  NUMBER(1)
);
COMMENT ON TABLE TYPES_ACTIONS IS 'Migrada de TBRGSA_TIPOACTUACION';
ALTER TABLE TYPES_ACTIONS ADD CONSTRAINT PK_TYPES_ACTIONS__ID PRIMARY KEY (ID);



create table PROVINCES
(
    ID                  NUMBER(12) NOT NULL,
    ENROLLMENT          VARCHAR2(3),
    NAME                VARCHAR2(30),
    PRE_POSTAL_CODE     VARCHAR2(3),
    ENROLLMENT_CCAA     VARCHAR2(5),
    ADDRESS             VARCHAR2(500),
    EMAIL               VARCHAR2(200),
    OLD                 NUMBER default '0' NOT NULL,
    OLD_TWO             NUMBER,
    OLD_THREE           NUMBER default 0,
    ID_STATE            NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_AT          TIMESTAMP(6),
    CREATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32)
);
ALTER TABLE PROVINCES ADD CONSTRAINT PK_PROVINCES__ID PRIMARY KEY (ID);



CREATE TABLE TYPE_EXPEDIENTS
(
    ID          NUMBER(12) NOT NULL,
    CODE        VARCHAR2(6 char)NOT NULL,
    NAME        VARCHAR2(250),
    ID_STATE    NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT  TIMESTAMP(6),
    CREATED_BY  NUMBER(32),
    UPDATED_AT  TIMESTAMP(6),
    UPDATED_BY  NUMBER(32)
);
ALTER TABLE TYPE_EXPEDIENTS ADD CONSTRAINT PK_TYPE_EXPEDIENTS__ID PRIMARY KEY (ID);
ALTER TABLE TYPE_EXPEDIENTS ADD CONSTRAINT UK_TYPE_EXPEDIENTS__CODE UNIQUE (CODE);



CREATE TABLE TYPE_CHANGE_EXPEDIENTS
(
    ID          NUMBER(12) NOT NULL,
    NAME        VARCHAR2(250),
    ID_STATE    NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT  TIMESTAMP(6),
    CREATED_BY  NUMBER(32),
    UPDATED_AT  TIMESTAMP(6),
    UPDATED_BY  NUMBER(32)
);
ALTER TABLE TYPE_CHANGE_EXPEDIENTS ADD CONSTRAINT PK_TYPE_CHANGE_EXPEDIENTS__ID PRIMARY KEY (ID);


CREATE TABLE EXPEDIENTS
(
    ID                      NUMBER(12) NOT NULL,
    NUMBER_EXPEDIENT        VARCHAR2(6),
    ID_INDUSTRY             NUMBER(12),
    NAME_BUSINESS           VARCHAR2(200),
    ID_PRODUCT             NUMBER(12),
    ID_DENOMINATION_SALE    NUMBER(12),
    BRAND                   VARCHAR2(200),
    ID_SITUATION            NUMBER(12),
    ID_KEY                  NUMBER(12),
    NUMBER_INDUSTRY         VARCHAR2(6),
    ADDRESS_BUSINESS        VARCHAR2(500),
    DATE_ADMISSION          DATE,
    DATE_ESTI_RESOLUTION    DATE,
    DATE_REPORT             DATE,
    DATE_RESOLUTION         DATE,
    ID_STATES               NUMBER(12),
    ELECTRONIC_FLOW         NUMBER(1),
    ID_COUNTRY              NUMBER(12),
    ID_PROVINCE             NUMBER(12),
    ID_USER_ASSIGNED        NUMBER(12),
    ID_USER_REPORT          NUMBER(12),
    ID_TYPE_EXPEDIENT       NUMBER(12),
    DATE_AUTHORIZATION      DATE,
    OBSERVATION             VARCHAR2(500),
    FOUNTAIN                VARCHAR2(200),
    LOCATION                VARCHAR2(200),
    ENROLLMENT_KEY_27       VARCHAR2(3),
    ID_COUNTRY_LOCATION     NUMBER(12),
    DATE_DOCE               DATE,
    ID_COUNTRY_FABRICATION  NUMBER(12),
    ID_COUNTRY_COMMERCIALIZATION NUMBER(12),
    OTHER_COUNTRY           VARCHAR2(200),
    TYPE_CONTAINER          VARCHAR2(200),
    INGREDIENT              VARCHAR2(2000),
    ID_FORM_PRESENTATION    NUMBER(12),
    DESCRIPTION_COUNTRY_LOCATION VARCHAR2(200),
    SOCIAL_REASON_KEY_26   VARCHAR2(200),
    PRODUCT_NAME_IA_KEY_26 VARCHAR2(200),
    ID_COUNTRY_IA_KEY_26   NUMBER(12),
    ADDRESS_IA_CODE_26      VARCHAR2(200),
    EMAIL_CODE_26           VARCHAR2(200),
    PHONE_IA_CODE_26        VARCHAR2(20),
    DATE_REQUEST_CHANGE     DATE,
    DATE_LAST_REQUEST       DATE,
    DATE_INSCRIPTION        DATE,
    DATE_OF_DENIAL          DATE,
    DATE_RESPONSE_AESAN     DATE,
    AUTHORITY               VARCHAR2(3),
    ID_TYPE_CHANGE_EXPEDIENTS   NUMBER(12),
    PRODUCT_UPDATED         NUMBER,
    SIGNATURE_APPLICATION   NUMBER DEFAULT 0,
    ENROLLMENT              VARCHAR2(3),
    TYPE_SUBSTANCE           NUMBER,
    INDUSTRY_EMAIL          VARCHAR2(200),
    INDUSTRY_PHONE          VARCHAR2(200),
    OTHER_COUNTRY_COMER     VARCHAR2(200),
    OTHER_FORMS             VARCHAR2(200),
    MIGRATION               VARCHAR2(4000),
    ID_STATE                NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_AT              TIMESTAMP(6),
    CREATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32)
);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT PK_EXPEDIENTS__ID PRIMARY KEY (ID);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT FK_EXPEDIENTS__ID_INDUSTRY FOREIGN KEY (ID_INDUSTRY) REFERENCES INDUSTRIES(ID);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT FK_EXPEDIENTS__ID_PRODUCT FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS(ID);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT FK_EXPEDIENTS__ID_DENOMINATION_SALE FOREIGN KEY (ID_DENOMINATION_SALE) REFERENCES DENOMINATION_SALES(ID);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT FK_EXPEDIENTS__ID_SITUATION FOREIGN KEY (ID_SITUATION) REFERENCES SITUATION(ID);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT FK_EXPEDIENTS__ID_KEY FOREIGN KEY (ID_KEY) REFERENCES KEYS(ID);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT FK_EXPEDIENTS__ID_COUNTRY FOREIGN KEY (ID_COUNTRY) REFERENCES COUNTRIES(ID);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT FK_EXPEDIENTS__ID_PROVINCE FOREIGN KEY (ID_PROVINCE) REFERENCES PROVINCES(ID);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT FK_EXPEDIENTS__ID_USER_ASSIGNED FOREIGN KEY (ID_USER_ASSIGNED) REFERENCES USERS(ID);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT FK_EXPEDIENTS__ID_USER_REPORT FOREIGN KEY (ID_USER_REPORT) REFERENCES USERS(ID);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT FK_EXPEDIENTS__ID_TYPE_EXPEDIENT FOREIGN KEY (ID_TYPE_EXPEDIENT) REFERENCES TYPE_EXPEDIENTS(ID);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT FK_EXPEDIENTS__ID_COUNTRY_LOCATION FOREIGN KEY (ID_COUNTRY_LOCATION) REFERENCES COUNTRIES(ID);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT FK_EXPEDIENTS__ID_COUNTRY_FABRICATION FOREIGN KEY (ID_COUNTRY_FABRICATION) REFERENCES COUNTRIES(ID);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT FK_EXPEDIENTS__ID_COUNTRY_COMMERCIALIZATION FOREIGN KEY (ID_COUNTRY_COMMERCIALIZATION) REFERENCES COUNTRIES(ID);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT FK_EXPEDIENTS__ID_FORM_PRESENTATION FOREIGN KEY (ID_FORM_PRESENTATION) REFERENCES FORM_PRESENTATION(ID);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT FK_EXPEDIENTS__ID_COUNTRY_IA_KEY_26 FOREIGN KEY (ID_COUNTRY_IA_KEY_26) REFERENCES COUNTRIES(ID);
ALTER TABLE EXPEDIENTS ADD CONSTRAINT FK_EXPEDIENTS__ID_TYPE_CHANGE_EXPEDIENTS FOREIGN KEY (ID_TYPE_CHANGE_EXPEDIENTS) REFERENCES TYPE_CHANGE_EXPEDIENTS(ID);


CREATE TABLE ACTIONS (
    ID                  NUMBER(12) NOT NULL,
    DESCRIPTION         VARCHAR2(200),
    ID_TYPES_ACTION     NUMBER(12),
    ID_INDUSTRY         NUMBER(12),
    ID_PRODUCT          NUMBER(12),
    ID_EXPEDIENT        NUMBER(12),
    NUMBER_FILES        NUMBER,
    TELEMATIC_REGISTER  VARCHAR2(25),
    ID_STATE            NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6)
);
COMMENT ON TABLE KEYS IS 'Migrada de TBRGSA_ACTUACIONES';
ALTER TABLE ACTIONS ADD CONSTRAINT PK_ACTIONS__ID PRIMARY KEY (ID);
ALTER TABLE ACTIONS ADD CONSTRAINT FK_ACTIONS__ID_TYPES_ACTION FOREIGN KEY (ID_TYPES_ACTION) REFERENCES TYPES_ACTIONS(ID);
ALTER TABLE ACTIONS ADD CONSTRAINT FK_ACTIONS__ID_INDUSTRY FOREIGN KEY (ID_INDUSTRY) REFERENCES INDUSTRIES(ID);
ALTER TABLE ACTIONS ADD CONSTRAINT FK_ACTIONS__ID_PRODUCT FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS(ID);
ALTER TABLE ACTIONS ADD CONSTRAINT FK_ACTIONS__ID_EXPEDIENT FOREIGN KEY (ID_EXPEDIENT) REFERENCES EXPEDIENTS(ID);



CREATE TABLE TYPES_DOCUMENTS
(
    ID                      NUMBER(12) NOT NULL,
    TYPE                    VARCHAR2(20),
    NAME                    VARCHAR2(200),
    TYPE_COMPANY_PRODUCT    NUMBER(32),
    VISIBLE_CCAA            NUMBER,
    NO_DELETE               NUMBER,
    ID_STATE                NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_BY              NUMBER(32),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6)
);
COMMENT ON TABLE TYPES_DOCUMENTS IS 'Migrada de TBRGSA_TIPODOC';
COMMENT ON COLUMN TYPES_DOCUMENTS.TYPE_COMPANY_PRODUCT IS '0:Industria; 1:Producto; 2:Ambos';
ALTER TABLE TYPES_DOCUMENTS ADD CONSTRAINT PK_TYPES_DOCUMENTS__ID PRIMARY KEY (ID);



CREATE TABLE DOCUMENTS
(
    ID                      NUMBER(32) NOT NULL,
    NAME                    VARCHAR2(200),
    ID_TYPES_FILES          NUMBER(12),     --TODO
    ID_INDUSTRY              NUMBER(12),
    ID_ACTION               NUMBER(12),
    ID_TYPE_DOCUMENT        NUMBER(12),
    ID_PRODUCT              NUMBER(12),
    ID_CASE_FILE            NUMBER(12),     --TODO
    NUMBER_EXIT             VARCHAR2(25),
    PATH_FILE               VARCHAR2(200),
    PATH_FILE_OLD           VARCHAR2(200),
    NAME_FILE               VARCHAR2(1000),
    ID_STATE                NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_BY              NUMBER(32),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6)
);
COMMENT ON TABLE DOCUMENTS IS 'Migrada de TBRGSA_DOCUMENTOS';
ALTER TABLE DOCUMENTS ADD CONSTRAINT PK_DOCUMENTS__ID PRIMARY KEY (ID);
ALTER TABLE DOCUMENTS ADD CONSTRAINT FK_DOCUMENTS__ID_INDUSTRY FOREIGN KEY (ID_INDUSTRY) REFERENCES INDUSTRIES(ID);
ALTER TABLE DOCUMENTS ADD CONSTRAINT FK_DOCUMENTS__ID_ACTION FOREIGN KEY (ID_ACTION) REFERENCES ACTIONS(ID);
ALTER TABLE DOCUMENTS ADD CONSTRAINT FK_DOCUMENTS__ID_TYPE_DOCUMENT FOREIGN KEY (ID_TYPE_DOCUMENT) REFERENCES TYPES_DOCUMENTS(ID);
ALTER TABLE DOCUMENTS ADD CONSTRAINT FK_DOCUMENTS__ID_PRODUCT FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS(ID);



CREATE TABLE LOCATIONS
(
    ID                      NUMBER(12) NOT NULL,
    NAME                    VARCHAR2(200),
    ENROLLMENT_PROVINCES    VARCHAR2(3),
    DESCRIPTION_PADRE       VARCHAR2(200),
    COMBO                   NUMBER,
    ID_LOCATIONS            VARCHAR2(12),
    CODE_INE                VARCHAR2(12),
    ID_STATE                NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_AT              TIMESTAMP(6)     not null,
    CREATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6)     not null,
    UPDATED_BY              NUMBER(32)
);
ALTER TABLE LOCATIONS ADD CONSTRAINT PK_LOCATIONS__ID PRIMARY KEY (ID);



CREATE TABLE AUTHORIZATIONS
(
    ID              NUMBER(12) NOT NULL,
    NAME            VARCHAR2(200) NOT NULL,
    ID_STATE        NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6)
);
ALTER TABLE AUTHORIZATIONS ADD CONSTRAINT PK_AUTHORIZATIONS__ID PRIMARY KEY (ID);



CREATE TABLE INDUSTRIES_AUTHORIZATIONS
(
    ID                  NUMBER(12) NOT NULL,
    ID_INDUSTRY         NUMBER(12),
    ID_AUTHORIZATION    NUMBER(12),
    ID_STATE            NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6)
);
ALTER TABLE INDUSTRIES_AUTHORIZATIONS ADD CONSTRAINT PK_INDUSTRIES_AUTHORIZATIONS__ID PRIMARY KEY (ID);
ALTER TABLE INDUSTRIES_AUTHORIZATIONS ADD CONSTRAINT FK_INDUSTRIES_AUTHORIZATIONS__ID_INDUSTRY FOREIGN KEY (ID_INDUSTRY) REFERENCES INDUSTRIES(ID);
ALTER TABLE INDUSTRIES_AUTHORIZATIONS ADD CONSTRAINT FK_INDUSTRIES_AUTHORIZATIONS__ID_AUTHORIZATION FOREIGN KEY (ID_AUTHORIZATION) REFERENCES AUTHORIZATIONS(ID);



CREATE TABLE ACTIVITIES
(
    ID                  NUMBER(12) NOT NULL,
    CODE                VARCHAR2(4),
    NAME                VARCHAR2(250),
    NUMBER_ACTIVITY     VARCHAR2(4),
    OLD                 VARCHAR2(1),
    KEY_OLD             NUMBER(2),
    IS_PUBLIC           NUMBER default 1,
    ID_STATE            NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6)
);
ALTER TABLE ACTIVITIES ADD CONSTRAINT PK_ACTIVITIES__ID PRIMARY KEY (ID);



CREATE TABLE SUB_ACTIVITIES
(
    ID              NUMBER(12) NOT NULL,
    NAME            VARCHAR2(250),
    ID_STATE        NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6)
);
ALTER TABLE SUB_ACTIVITIES ADD CONSTRAINT PK_SUB_ACTIVITIES__ID PRIMARY KEY (ID);



CREATE TABLE KEYS_ACTIVITIES_CATEGORIES
(
    KEY                 NUMBER(12)              not null,
    CATEGORY            NUMBER(32)              not null,
    ACTIVITY            VARCHAR2(4)             not null,
    SUB_ACTIVITY        NUMBER  default 0       not null,
    IS_VISIBLE_UE       NUMBER                  default 1,
    IS_VISIBLE_RGSA     NUMBER                  default 1
);
comment on table KEYS_ACTIVITIES_CATEGORIES is 'Tabla de relaciones entre Clave de Industria, Actividades, Categorias y Subactividades';



CREATE TABLE INDUSTRIES_KEYS_ACTIVITIES_CATEGORIES
(
    ID                  NUMBER(12) NOT NULL,
    ID_INDUSTRY         NUMBER(12),
    ID_KEY              NUMBER(12),
    ID_CATEGORY         NUMBER(12),
    CODE_ACTIVITY       VARCHAR2(4),
    ID_SUB_ACTIVITY     NUMBER(12)  DEFAULT 0 NOT NULL,
    ID_STATE            NUMBER(10)  DEFAULT 1 NOT NULL,
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6)
);
ALTER TABLE INDUSTRIES_KEYS_ACTIVITIES_CATEGORIES ADD CONSTRAINT PK_INDUSTRIES_KEYS_ACTIVITIES_CATEGORIES__ID PRIMARY KEY (ID);
ALTER TABLE INDUSTRIES_KEYS_ACTIVITIES_CATEGORIES ADD CONSTRAINT FK_INDUSTRIES_KEYS_ACTIVITIES_CATEGORIES__ID_INDUSTRY FOREIGN KEY (ID_INDUSTRY) REFERENCES INDUSTRIES(ID);
ALTER TABLE INDUSTRIES_KEYS_ACTIVITIES_CATEGORIES ADD CONSTRAINT FK_INDUSTRIES_KEYS_ACTIVITIES_CATEGORIES__ID_KEY FOREIGN KEY (ID_KEY) REFERENCES KEYS(ID);
ALTER TABLE INDUSTRIES_KEYS_ACTIVITIES_CATEGORIES ADD CONSTRAINT FK_INDUSTRIES_KEYS_ACTIVITIES_CATEGORIES__ID_CATEGORY FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORIES(ID);



CREATE TABLE TYPE_SUBSTANCES
(
    ID              NUMBER(32) NOT NULL,
    NAME            VARCHAR2(255 char) NOT NULL,
    ID_STATE        NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP(6),
    CREATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32)
);
ALTER TABLE TYPE_SUBSTANCES ADD CONSTRAINT PK_TYPE_SUBSTANCES__ID PRIMARY KEY (ID);

