CREATE SEQUENCE SEQ_ACTIONS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_AUTHORIZATIONS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_DOCUMENTS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_ENTITIES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_ENTITIES_TYPES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_INDUSTRIES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_COMPANIES_AUTHORIZATIONS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_MODULES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_MODULES_TYPES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_PERMISSIONS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_PRODUCTS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_PROFILES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_PROFILES_PERMISSIONS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_USERS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_USERS_MODELS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_USERS_PROFILES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_ACTIVITIES START WITH 600 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_INDUSTRIES_KEYS_ACTIVITIES_CATEGORIES START WITH 10000 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_TYPE_EXPEDIENTS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_TYPE_CHANGE_EXPEDIENTS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_EXPEDIENTS START WITH 10000 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_SUBSTANCES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_TYPES_DOCUMENTS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_ACTIVITIES_KEYS_CATEGORIES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_ACTIVITIES_KEYS_CATEGORIES_SUBACTIVITIES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_RGSEAA START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_RGSEAA_ACTIVITIES START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_TYPES_ACTUATIONS START WITH 100 INCREMENT BY 1 CACHE 30;
CREATE SEQUENCE SEQ_COMPANIES_ACTUATIONS START WITH 100 INCREMENT BY 1 CACHE 30;



CREATE TABLE AUTHORIZATIONS
(
    ID              NUMBER(12) DEFAULT SEQ_AUTHORIZATIONS.nextval NOT NULL,
    NAME            VARCHAR2(200) NOT NULL,
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE AUTHORIZATIONS ADD CONSTRAINT PK_AUTHORIZATIONS__ID PRIMARY KEY (ID);

CREATE TABLE STATES (
    ID              NUMBER(12) DEFAULT SEQ_STATES.nextval NOT NULL,
    CODE            VARCHAR2(30),
    NAME            VARCHAR2(30),
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL

);
ALTER TABLE STATES ADD CONSTRAINT PK_STATES__ID PRIMARY KEY (ID);


CREATE TABLE PERMISSIONS
(
    ID              NUMBER(12) DEFAULT SEQ_PERMISSIONS.nextval NOT NULL,
    CODE            VARCHAR2(100 char),
    DESCRIPTION     VARCHAR2(100 char),
    NAME            VARCHAR2(20 char) NOT NULL,
    CREATED_AT      TIMESTAMP(6),
    CREATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE PERMISSIONS ADD CONSTRAINT PK_PERMISSIONS__ID PRIMARY KEY (ID);


CREATE TABLE PROFILES
(
    ID          NUMBER(12) DEFAULT SEQ_PROFILES.nextval NOT NULL,
    NAME        VARCHAR2(255 char) NOT NULL,
    CREATED_AT  TIMESTAMP(6),
    CREATED_BY  NUMBER(32),
    UPDATED_AT  TIMESTAMP(6),
    UPDATED_BY  NUMBER(32),
    STATE        NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE PROFILES ADD CONSTRAINT PK_PROFILES__ID PRIMARY KEY (ID);


CREATE TABLE PROFILES_PERMISSIONS
(
    ID            NUMBER(12) DEFAULT SEQ_PROFILES_PERMISSIONS.nextval NOT NULL,
    PERMISSION_ID NUMBER(32) NOT NULL,
    PROFILE_ID    NUMBER(32) NOT NULL,
    CREATED_AT    TIMESTAMP(6) not null,
    CREATED_BY    NUMBER(32),
    UPDATED_AT    TIMESTAMP(6) not null,
    UPDATED_BY    NUMBER(32),
    STATE      NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE PROFILES_PERMISSIONS ADD CONSTRAINT PK_PROFILES_PERMISSIONS__ID PRIMARY KEY (ID);
ALTER TABLE PROFILES_PERMISSIONS ADD CONSTRAINT FK_PROFILES_PERMISSIONS__PERMISSION_ID FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(ID);
ALTER TABLE PROFILES_PERMISSIONS ADD CONSTRAINT FK_PROFILES_PERMISSIONS__PROFILE_ID FOREIGN KEY (PROFILE_ID) REFERENCES PROFILES(ID);


CREATE TABLE USERS
(
    ID             NUMBER(12) DEFAULT SEQ_USERS.nextval NOT NULL,
    NIF            VARCHAR2(9 char),
    NAME           VARCHAR2(255 char),
    FIRST_SURNAME  VARCHAR2(255 char),
    SECOND_SURNAME VARCHAR2(255 char),
    EMAIL          VARCHAR2(255 char),
    PHONE          VARCHAR2(255 char),
    CREATED_AT     TIMESTAMP(6),
    CREATED_BY     NUMBER(32),
    UPDATED_AT     TIMESTAMP(6),
    UPDATED_BY     NUMBER(32),
    STATE       NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE USERS ADD CONSTRAINT PK_USERS__ID PRIMARY KEY (ID);
ALTER TABLE USERS ADD CONSTRAINT UK_USERS__NIF UNIQUE (NIF);


CREATE TABLE ENTITIES_TYPES
(
    ID              NUMBER(12) DEFAULT SEQ_ENTITIES_TYPES.nextval NOT NULL,
    DESCRIPTION     VARCHAR2(255 char),
    NAME            VARCHAR2(255 char) NOT NULL,
    CREATED_AT      TIMESTAMP(6),
    CREATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    STATE        NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE ENTITIES_TYPES ADD CONSTRAINT PK_ENTITIES_TYPES__ID PRIMARY KEY (ID);


CREATE TABLE ENTITIES
(
    ID              NUMBER(12) DEFAULT SEQ_ENTITIES.nextval NOT NULL,
    NAME            VARCHAR2(100 char) NOT NULL,
    DESCRIPTION     VARCHAR2(100 char) NOT NULL,
    CODE            VARCHAR2(6 char) NOT NULL,
    TYPE_ID         NUMBER(32)  NOT NULL,
    ADDRESS         VARCHAR2(255 char),
    CONTACT_PERSON  VARCHAR2(255 char),
    EMAIL           VARCHAR2(255 char),
    PHONE           VARCHAR2(255 char),
    POSTAL_CODE     VARCHAR2(255 char),
    ROOT_ENTITY     NUMBER(1),
    CREATED_AT      TIMESTAMP(6)     not null,
    CREATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6)     not null,
    UPDATED_BY      NUMBER(32),
    STATE        NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE ENTITIES ADD CONSTRAINT PK_ENTITIES__ID PRIMARY KEY (ID);
ALTER TABLE ENTITIES ADD CONSTRAINT UK_ENTITIES__CODE UNIQUE (CODE);
ALTER TABLE ENTITIES ADD CONSTRAINT FK_ENTITIES__ID_TYPE FOREIGN KEY (TYPE_ID) REFERENCES ENTITIES_TYPES(ID);

CREATE TABLE USERS_ENTITIES
(
    ENTITY_ID  NUMBER(12)  NOT NULL,
    USER_ID    NUMBER(12)  NOT NULL,
    SCOPE_CODE VARCHAR2(20 char) NOT NULL,
    STATE   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE USERS_ENTITIES ADD CONSTRAINT PK_USERS_ENTITIES PRIMARY KEY (ENTITY_ID,USER_ID);
ALTER TABLE USERS_ENTITIES ADD CONSTRAINT FK_USERS_ENTITIES__ENTITY_ID FOREIGN KEY (ENTITY_ID) REFERENCES ENTITIES(ID);
ALTER TABLE USERS_ENTITIES ADD CONSTRAINT FK_USERS_ENTITIES__USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID);


CREATE TABLE MODULES_TYPES
(
    ID              NUMBER(12) DEFAULT SEQ_MODULES_TYPES.nextval  NOT NULL,
    NAME            VARCHAR2(100),
    DESCRIPTION            VARCHAR2(200),
    CREATED_AT      TIMESTAMP(6),
    CREATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    STATE        NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE MODULES_TYPES ADD CONSTRAINT PK_MODULES_TYPES__ID PRIMARY KEY (ID);


CREATE TABLE MODULES
(
    ID          NUMBER(12) DEFAULT SEQ_MODULES.nextval NOT NULL,
    CODE        VARCHAR2(6 char) NOT NULL,
    NAME        VARCHAR2(100),
    TYPE_ID     NUMBER(12),
    CREATED_AT  TIMESTAMP(6),
    CREATED_BY  NUMBER(32),
    UPDATED_AT  TIMESTAMP(6),
    UPDATED_BY  NUMBER(32),
    STATE    NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE MODULES ADD CONSTRAINT PK_MODULES__ID PRIMARY KEY (ID);
ALTER TABLE MODULES ADD CONSTRAINT UK_MODULES__CODE UNIQUE (CODE);
ALTER TABLE MODULES ADD CONSTRAINT FK_MODULES__ID_TYPE FOREIGN KEY (TYPE_ID) REFERENCES MODULES_TYPES(ID);


CREATE TABLE USERS_MODELS
(
    ID         NUMBER(12) DEFAULT SEQ_USERS_MODELS.nextval NOT NULL,
    MODULE_ID  NUMBER(12),
    USER_ID    NUMBER(12),
    CREATED_AT TIMESTAMP(6),
    CREATED_BY NUMBER(32),
    UPDATED_AT TIMESTAMP(6),
    UPDATED_BY NUMBER(32),
    STATE   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE USERS_MODELS ADD CONSTRAINT PK_USERS_MODELS_ID PRIMARY KEY (ID);
ALTER TABLE USERS_MODELS ADD CONSTRAINT FK_USERS_MODELS__MODULE_ID FOREIGN KEY (MODULE_ID) REFERENCES MODULES(ID);
ALTER TABLE USERS_MODELS ADD CONSTRAINT FK_USERS_MODELS__USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID);


CREATE TABLE USERS_PROFILES
(
    ID          NUMBER(12) DEFAULT SEQ_USERS_PROFILES.nextval NOT NULL,
    PROFILE_ID  NUMBER(12),
    USER_ID     NUMBER(12),
    CREATED_AT  TIMESTAMP(6) NOT NULL,
    CREATED_BY  NUMBER(32),
    UPDATED_AT  TIMESTAMP(6),
    UPDATED_BY  NUMBER(12),
    STATE   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE USERS_PROFILES ADD CONSTRAINT PK_USERS_PROFILES_ID PRIMARY KEY (ID);
ALTER TABLE USERS_PROFILES ADD CONSTRAINT FK_USERS_PROFILES__PROFILE_ID FOREIGN KEY (PROFILE_ID) REFERENCES PROFILES(ID);
ALTER TABLE USERS_PROFILES ADD CONSTRAINT FK_USERS_PROFILES__USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID);


CREATE TABLE COUNTRIES (
    ID                  NUMBER(32) default SEQ_COUNTRIES.nextval NOT NULL,
    NAME                VARCHAR2(50),
    ENROLLMENT          VARCHAR2(3),
    NO_DELETE           NUMBER,
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6),
    STATE            NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE COUNTRIES ADD CONSTRAINT PK_COUNTRIES__ID PRIMARY KEY (ID);


create table PROVINCES
(
    ID                  NUMBER(12) default SEQ_PROVINCES.nextval NOT NULL,
    ENROLLMENT          VARCHAR2(3),
    NAME                VARCHAR2(30),
    PRE_POSTAL_CODE     VARCHAR2(3),
    ENROLLMENT_CCAA     VARCHAR2(5),
    ADDRESS             VARCHAR2(500),
    EMAIL               VARCHAR2(200),
    OLD                 NUMBER default '0' NOT NULL,
    OLD_TWO             NUMBER,
    OLD_THREE           NUMBER default 0,
    CREATED_AT          TIMESTAMP(6),
    CREATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    STATE            NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE PROVINCES ADD CONSTRAINT PK_PROVINCES__ID PRIMARY KEY (ID);



CREATE TABLE LOCATIONS
(
    ID                      NUMBER(12) DEFAULT  SEQ_LOCATIONS.nextval NOT NULL,
    NAME                    VARCHAR2(200),
    ENROLLMENT_PROVINCES    VARCHAR2(3),
    DESCRIPTION_PADRE       VARCHAR2(200),
    COMBO                   NUMBER,
    LOCATIONS_ID            VARCHAR2(12),
    CODE_INE                VARCHAR2(12),
    CREATED_AT              TIMESTAMP(6)     not null,
    CREATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6)     not null,
    UPDATED_BY              NUMBER(32),
    STATE                NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE LOCATIONS ADD CONSTRAINT PK_LOCATIONS__ID PRIMARY KEY (ID);


CREATE TABLE SITUATIONS (
    ID                      NUMBER(12) DEFAULT SEQ_SITUATIONS.nextval NOT NULL,
    NAME                    VARCHAR2(50),
    TYPE_COMPANY_PRODUCT   NUMBER,
    NEW_OPTION              NUMBER,
    NO_DELETE               NUMBER DEFAULT 0,
    VISIBLE_RGSA            NUMBER DEFAULT 1,
    VISIBLE_UE              NUMBER DEFAULT 1,
    CREATED_BY              NUMBER(32),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6),
    STATE                NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE SITUATIONS ADD CONSTRAINT PK_SITUATION__ID PRIMARY KEY (ID);


CREATE TABLE COMPANIES
(
    ID                      NUMBER(12) DEFAULT SEQ_INDUSTRIES.nextval NOT NULL,
    NIF                     VARCHAR2(20),
    NAME                    VARCHAR2(200),
    EMAIL                   VARCHAR2(50),
    PAGE_WEB                VARCHAR2(200),
    OBSERVATION             VARCHAR2(2000),
    ADDRESS                 VARCHAR2(500),
    POSTAL_CODE             VARCHAR2(20),
    COUNTRY_ID              NUMBER(12),
    PROVINCE_ID             NUMBER(12),
    LOCATION_ID             NUMBER(12),
    SITUATION_ID            NUMBER(12),
    CREATED_BY              NUMBER(12),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(12),
    UPDATED_AT              TIMESTAMP(6),
    STATE                NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE COMPANIES ADD CONSTRAINT PK_INDUSTRIES__ID PRIMARY KEY (ID);
ALTER TABLE COMPANIES ADD CONSTRAINT FK_INDUSTRIES__COUNTRY_ID FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(ID);
ALTER TABLE COMPANIES ADD CONSTRAINT FK_INDUSTRIES__PROVINCE_ID FOREIGN KEY (PROVINCE_ID) REFERENCES PROVINCES(ID);
ALTER TABLE COMPANIES ADD CONSTRAINT FK_INDUSTRIES__LOCATION_ID FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(ID);
ALTER TABLE COMPANIES ADD CONSTRAINT FK_INDUSTRIES__SITUATION_ID FOREIGN KEY (SITUATION_ID) REFERENCES SITUATIONS(ID);


CREATE TABLE ESTABLISHMENTS
(
    ID                      NUMBER(12) default SEQ_ESTABLISHMENTS.nextval NOT NULL,
    COMPANY_ID              NUMBER(12) NOT NULL,
    ADDRESS                 VARCHAR2(500),
    POSTAL_CODE             VARCHAR2(20),
    COUNTRY_ID              NUMBER(12),
    PROVINCE_ID             NUMBER(12),
    LOCATION_ID             NUMBER(12),
    SITUATION_ID            NUMBER(12),
    CREATED_BY              NUMBER(12),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(12),
    UPDATED_AT              TIMESTAMP(6),
    STATE                NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE ESTABLISHMENTS ADD CONSTRAINT PK_ESTABLISHMENTS__ID PRIMARY KEY (ID);
ALTER TABLE ESTABLISHMENTS ADD CONSTRAINT FK_ESTABLISHMENTS__COUNTRY_ID FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(ID);
ALTER TABLE ESTABLISHMENTS ADD CONSTRAINT FK_ESTABLISHMENTS__PROVINCE_ID FOREIGN KEY (PROVINCE_ID) REFERENCES PROVINCES(ID);
ALTER TABLE ESTABLISHMENTS ADD CONSTRAINT FK_ESTABLISHMENTS__LOCATION_ID FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(ID);
ALTER TABLE ESTABLISHMENTS ADD CONSTRAINT FK_ESTABLISHMENTS__SITUATION_ID FOREIGN KEY (SITUATION_ID) REFERENCES SITUATIONS(ID);


CREATE TABLE TYPES_ACTIONS
(
    ID                      NUMBER(12) DEFAULT SEQ_TYPES_ACTIONS.nextval NOT NULL,
    NAME                    VARCHAR2(250),
    TYPE_COMPANY_PRODUCT_ID NUMBER(12),
    VISIBLE_CCAA            NUMBER,
    NO_DELETE               NUMBER,
    CREATED_BY              NUMBER(32),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6),
    STATUS                  NUMBER(1),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE TYPES_ACTIONS ADD CONSTRAINT PK_TYPES_ACTIONS__ID PRIMARY KEY (ID);



CREATE TABLE ACTIONS (
    ID                  NUMBER(12) DEFAULT SEQ_ACTIONS.nextval NOT NULL,
    DESCRIPTION         VARCHAR2(200),
    TYPES_ACTION_ID     NUMBER(12),
    COMPANY_ID         NUMBER(12),
    PRODUCT_ID          NUMBER(12),
    NUMBER_FILES        NUMBER,
    TELEMATIC_REGISTER  VARCHAR2(25),
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6),
    STATE               NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE ACTIONS ADD CONSTRAINT PK_ACTIONS__ID PRIMARY KEY (ID);
ALTER TABLE ACTIONS ADD CONSTRAINT FK_ACTIONS__TYPES_ACTION_ID FOREIGN KEY (TYPES_ACTION_ID) REFERENCES TYPES_ACTIONS(ID);
ALTER TABLE ACTIONS ADD CONSTRAINT FK_ACTIONS__COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID); -- TODO


CREATE TABLE TYPES_DOCUMENTS
(
    ID                      NUMBER(12) DEFAULT SEQ_TYPES_DOCUMENTS.nextval NOT NULL,
    TYPE                    VARCHAR2(20),
    NAME                    VARCHAR2(200),
    TYPE_COMPANY_PRODUCT    NUMBER(32),
    VISIBLE_CCAA            NUMBER,
    NO_DELETE               NUMBER,
    CREATED_BY              NUMBER(32),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE TYPES_DOCUMENTS ADD CONSTRAINT PK_TYPES_DOCUMENTS__ID PRIMARY KEY (ID);



CREATE TABLE DOCUMENTS
(
    ID                      NUMBER(32) DEFAULT SEQ_DOCUMENTS.nextval NOT NULL,
    NAME                    VARCHAR2(200),
    TYPES_FILES_ID          NUMBER(12),
    COMPANY_ID              NUMBER(12),
    ACTION_ID               NUMBER(12),
    TYPE_DOCUMENT_ID        NUMBER(12),
    PRODUCT_ID              NUMBER(12),
    CASE_FILE_ID            NUMBER(12),
    NUMBER_EXIT             VARCHAR2(25),
    PATH_FILE               VARCHAR2(200),
    PATH_FILE_OLD           VARCHAR2(200),
    NAME_FILE               VARCHAR2(1000),
    CREATED_BY              NUMBER(32),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE DOCUMENTS ADD CONSTRAINT PK_DOCUMENTS__ID PRIMARY KEY (ID);
ALTER TABLE DOCUMENTS ADD CONSTRAINT FK_DOCUMENTS__COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID);
ALTER TABLE DOCUMENTS ADD CONSTRAINT FK_DOCUMENTS__ACTION_ID FOREIGN KEY (ACTION_ID) REFERENCES ACTIONS(ID);
ALTER TABLE DOCUMENTS ADD CONSTRAINT FK_DOCUMENTS__TYPE_DOCUMENT_ID FOREIGN KEY (TYPE_DOCUMENT_ID) REFERENCES TYPES_DOCUMENTS(ID);



CREATE TABLE TYPE_CHANGE_EXPEDIENTS
(
    ID              NUMBER(12) DEFAULT SEQ_TYPE_CHANGE_EXPEDIENTS.nextval NOT NULL,
    NAME            VARCHAR2(250),
    CREATED_AT      TIMESTAMP(6),
    CREATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    STATE        NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE TYPE_CHANGE_EXPEDIENTS ADD CONSTRAINT PK_TYPE_CHANGE_EXPEDIENTS__ID PRIMARY KEY (ID);


CREATE TABLE CATEGORIES (
    ID              NUMBER(12) DEFAULT SEQ_CATEGORIES.NEXTVAL NOT NULL,
    NAME            VARCHAR2(200),
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    STATE        NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE CATEGORIES ADD CONSTRAINT PK_CATEGORIES__ID PRIMARY KEY (ID);


CREATE TABLE AUTH_USER_REQUEST
(
    PETITION_ID        VARCHAR2(36)   NOT NULL,
    RELAY_ID           VARCHAR2(20)   NOT NULL,
    TOKEN              VARCHAR2(4000) NOT NULL,
    EXP                NUMBER(38)     NOT NULL,
    PROCESS_RETURN_URL VARCHAR2(4000) NOT NULL
);
ALTER TABLE AUTH_USER_REQUEST ADD CONSTRAINT PK_AUTH_USER_REQUEST__PETITION_ID PRIMARY KEY (PETITION_ID);
ALTER TABLE AUTH_USER_REQUEST ADD CONSTRAINT PK_AUTH_USER_REQUEST__RELAY_ID UNIQUE (RELAY_ID);



CREATE TABLE AUTH_USER_TOKEN
(
    PETITION_ID VARCHAR2(36)   NOT NULL,
    RELAY_ID    VARCHAR2(20)   NOT NULL,
    DOC_NUM     VARCHAR2(50)   NOT NULL,
    TOKEN       VARCHAR2(4000) NOT NULL,
    EXP         NUMBER(38)     NOT NULL
);
ALTER TABLE AUTH_USER_TOKEN ADD CONSTRAINT PK_AUTH_USER_TOKEN__PETITION_ID PRIMARY KEY (PETITION_ID);
ALTER TABLE AUTH_USER_TOKEN ADD CONSTRAINT UK_AUTH_USER_TOKEN__RELAY_ID UNIQUE (RELAY_ID);


CREATE TABLE KEYS (
    ID                  NUMBER(12) DEFAULT SEQ_KEYS.nextval NOT NULL,
    NAME                VARCHAR2(200),
    DATE_REGISTER       DATE,
    DATE_UNREGISTER     DATE,
    ALLOW_PRODUCT       NUMBER,
    IS_OLD              NUMBER DEFAULT 0,
    IS_PUBLIC           NUMBER DEFAULT 1,
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6),
    STATE            NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE KEYS ADD CONSTRAINT PK_CLAVE__ID PRIMARY KEY (ID);


CREATE TABLE ACTIVITIES
(
    ID                  NUMBER(12) DEFAULT SEQ_ACTIVITIES.nextval NOT NULL,
    CODE                VARCHAR2(4),
    NAME                VARCHAR2(250),
    IS_PUBLIC           NUMBER DEFAULT 1 NOT NULL,
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6),
    STATE            NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE ACTIVITIES ADD CONSTRAINT PK_ACTIVITIES__ID PRIMARY KEY (ID);


CREATE TABLE DENOMINATION_SALES (
    ID              NUMBER(12) DEFAULT SEQ_DENOMINATION_SALES.nextval NOT NULL,
    NAME            VARCHAR2(200),
    KEY_ID          NUMBER(12),
    ACTIVITY_ID     NUMBER(12),
    FILE_TYPE       VARCHAR2(5),
    IS_PUBLIC       NUMBER(1) DEFAULT 0,
    DATE_REGISTER   DATE,
    DATE_UNREGISTER DATE,
    ACTIVE          NUMBER(1) DEFAULT 1,
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    STATE        NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE DENOMINATION_SALES ADD CONSTRAINT PK_DENOMINATION_SALES__ID PRIMARY KEY (ID);
ALTER TABLE DENOMINATION_SALES ADD CONSTRAINT FK_DENOMINATION_SALES__KEY_ID FOREIGN KEY (KEY_ID) REFERENCES KEYS(ID);
ALTER TABLE DENOMINATION_SALES ADD CONSTRAINT FK_DENOMINATION_SALES__ACTIVITY_ID FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES(ID);



CREATE TABLE SUB_ACTIVITIES
(
    ID              NUMBER(12) DEFAULT SEQ_SUB_ACTIVITIES.NEXTVAL NOT NULL,
    NAME            VARCHAR2(250),
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    STATE        NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE SUB_ACTIVITIES ADD CONSTRAINT PK_SUB_ACTIVITIES__ID PRIMARY KEY (ID);


CREATE TABLE ACTIVITIES_KEYS (
    ID              NUMBER(12) DEFAULT SEQ_ACTIVITIES_KEYS.nextval  NOT NULL,
    KEY_ID          NUMBER(12) NOT NULL,
    ACTIVITY_ID     NUMBER(12) NOT NULL,
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE ACTIVITIES_KEYS ADD CONSTRAINT PK_ACTIVITIES_KEYS__ID PRIMARY KEY (ID);
ALTER TABLE ACTIVITIES_KEYS ADD CONSTRAINT FK_ACTIVITIES_KEYS__KEY_ID          FOREIGN KEY (KEY_ID)      REFERENCES KEYS(ID);
ALTER TABLE ACTIVITIES_KEYS ADD CONSTRAINT FK_ACTIVITIES_KEYS__ACTIVITY_ID     FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES(ID);

CREATE TABLE ACTIVITIES_KEYS_CATEGORIES(
    ID              NUMBER(12) DEFAULT SEQ_ACTIVITIES_KEYS_CATEGORIES.nextval  NOT NULL,
    ACTIVITY_KEY_ID NUMBER(12) NOT NULL,
	CATEGORY_ID     NUMBER(12) NOT NULL,
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE ACTIVITIES_KEYS_CATEGORIES ADD CONSTRAINT PK_ACTIVITIES_KEYS_CATEGORIES__ID PRIMARY KEY (ID);
ALTER TABLE ACTIVITIES_KEYS_CATEGORIES ADD CONSTRAINT FK_ACTIVITIES_KEYS_CATEGORIES__ACTIVITY_KEY_ID FOREIGN KEY (ACTIVITY_KEY_ID)   REFERENCES ACTIVITIES_KEYS(ID);
ALTER TABLE ACTIVITIES_KEYS_CATEGORIES ADD CONSTRAINT FK_ACTIVITIES_KEYS_CATEGORIES__CATEGORY_ID     FOREIGN KEY (CATEGORY_ID)       REFERENCES CATEGORIES(ID);



CREATE TABLE ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES(
    ID                       NUMBER(12) DEFAULT SEQ_ACTIVITIES_KEYS_CATEGORIES_SUBACTIVITIES.nextval  NOT NULL,
    ACTIVITY_KEY_CATEGORY_ID NUMBER(12) NOT NULL,
	SUB_ACTIVITY_ID          NUMBER(12) NOT NULL,
    CREATED_BY               NUMBER(32),
    CREATED_AT               TIMESTAMP(6),
    UPDATED_BY               NUMBER(32),
    UPDATED_AT               TIMESTAMP(6),
    STATE                    NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES ADD CONSTRAINT PK_ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES__ID PRIMARY KEY (ID);
ALTER TABLE ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES ADD CONSTRAINT FK_ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES__ACTIVITY_KEY_CATEGORY_ID  FOREIGN KEY (ACTIVITY_KEY_CATEGORY_ID)  REFERENCES ACTIVITIES_KEYS_CATEGORIES(ID);
ALTER TABLE ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES ADD CONSTRAINT FK_ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES__SUB_ACTIVITY_ID           FOREIGN KEY (SUB_ACTIVITY_ID)           REFERENCES SUB_ACTIVITIES(ID);


CREATE TABLE FORM_PRESENTATION (
    ID                  NUMBER(12) DEFAULT SEQ_FORM_PRESENTATION.nextval NOT NULL,
    NAME                VARCHAR2(200),
    TYPE                VARCHAR2(5),
    DATE_REGISTER       DATE,
    DATE_UNREGISTER     DATE,
    CREATED_BY          NUMBER(32),
    CREATED_AT          TIMESTAMP(6),
    UPDATED_BY          NUMBER(32),
    UPDATED_AT          TIMESTAMP(6),
    STATE            NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE FORM_PRESENTATION ADD CONSTRAINT PK_FORM_PRESENTATION__ID PRIMARY KEY (ID);


CREATE TABLE RGSEAA
(
    ID                      NUMBER(12) DEFAULT SEQ_RGSEAA.nextval NOT NULL,
    COMPANY_ID              NUMBER(12) DEFAULT NULL,
    ESTABLISHMENT_ID        NUMBER(12) DEFAULT NULL,
    KEY_ID                  NUMBER(12),
    NUM_RGSEAA              NUMBER(12),
    ENROLLMENT              VARCHAR2(3),
    CREATED_BY              NUMBER(12),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(12),
    UPDATED_AT              TIMESTAMP(6),
    STATE                NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE RGSEAA ADD CONSTRAINT PK_RGSEAA__ID PRIMARY KEY (ID);
ALTER TABLE RGSEAA ADD CONSTRAINT FK_RGSEAA__COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID);
ALTER TABLE RGSEAA ADD CONSTRAINT FK_RGSEAA__ESTABLISHMENT_ID FOREIGN KEY (ESTABLISHMENT_ID) REFERENCES ESTABLISHMENTS(ID);
ALTER TABLE RGSEAA ADD CONSTRAINT FK_RGSEAA__KEY_ID FOREIGN KEY (KEY_ID) REFERENCES KEYS(ID);



CREATE TABLE RGSEAA_ACTIVITY
(
    ID                      NUMBER(12) DEFAULT SEQ_RGSEAA_ACTIVITIES.nextval NOT NULL,
    RGSEAA_ID               NUMBER(12),
    ACTIVITY_ID             NUMBER(12),
    CATEGORY_ID             NUMBER(12),
    SUB_ACTIVITY_ID         NUMBER(12),
    CREATED_BY              NUMBER(12),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(12),
    UPDATED_AT              TIMESTAMP(6),
    STATE                NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE RGSEAA_ACTIVITY ADD CONSTRAINT PK_RGSEAA_ACTIVITY__ID PRIMARY KEY (ID);
ALTER TABLE RGSEAA_ACTIVITY ADD CONSTRAINT FK_RGSEAA_ACTIVITY__ACTIVITY_ID FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES(ID);
ALTER TABLE RGSEAA_ACTIVITY ADD CONSTRAINT FK_RGSEAA_ACTIVITY__CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID);


CREATE TABLE SUBSTANCES
(
    ID              NUMBER(12) DEFAULT SEQ_SUBSTANCES.nextval NOT NULL,
    NAME            VARCHAR2(255 char) NOT NULL,
    CREATED_AT      TIMESTAMP(6),
    CREATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    STATE                NUMBER(1) DEFAULT 1 NOT NULL
);
ALTER TABLE SUBSTANCES ADD CONSTRAINT PK_SUBSTANCES__ID PRIMARY KEY (ID);



CREATE TABLE COMPANIES_AUTHORIZATIONS(
    ID              NUMBER(12) DEFAULT SEQ_COMPANIES_AUTHORIZATIONS.nextval NOT NULL,
    COMPANY_ID      NUMBER(12)  NULL,
    ESTABLISHMENT_ID NUMBER(12) NULL,
    AUTHORIZATION_ID NUMBER(12) NOT NULL,
    CREATED_BY      NUMBER(32),
    CREATED_AT      TIMESTAMP(6),
    UPDATED_BY      NUMBER(32),
    UPDATED_AT      TIMESTAMP(6),
    STATE           NUMBER(1) DEFAULT 1 NOT NULL

);
ALTER TABLE COMPANIES_AUTHORIZATIONS ADD CONSTRAINT PK_COMPANIES_AUTHORIZATIONS__ID PRIMARY KEY (ID);
ALTER TABLE COMPANIES_AUTHORIZATIONS ADD CONSTRAINT FK_COMPANIES_AUTHORIZATIONS__COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID);
ALTER TABLE COMPANIES_AUTHORIZATIONS ADD CONSTRAINT FK_COMPANIES_AUTHORIZATIONS__ESTABLISHMENT_ID FOREIGN KEY (ESTABLISHMENT_ID) REFERENCES ESTABLISHMENTS(ID);
ALTER TABLE COMPANIES_AUTHORIZATIONS ADD CONSTRAINT FK_COMPANIES_AUTHORIZATIONS__AUTHORIZATION_ID FOREIGN KEY (AUTHORIZATION_ID) REFERENCES AUTHORIZATIONS(ID);


CREATE VIEW COMPANIES_ESTABLISHMENTS_VIEW AS
SELECT
    'PRINCIPAL' AS TYPE,
    c.ID AS COMPANY_ID,
    c.NIF,
    c.NAME AS COMPANY_NAME,
    c.EMAIL AS COMPANY_EMAIL,
    c.PAGE_WEB AS COMPANY_PAGE_WEB,
    c.OBSERVATION AS COMPANY_OBSERVATION,
    c.ADDRESS AS COMPANY_ADDRESS,
    c.POSTAL_CODE AS COMPANY_POSTAL_CODE,
    c.COUNTRY_ID AS COMPANY_COUNTRY_ID,
    c.PROVINCE_ID AS COMPANY_PROVINCE_ID,
    c.LOCATION_ID AS COMPANY_LOCATION_ID,
    c.SITUATION_ID AS COMPANY_SITUATION_ID,
    c.STATE AS COMPANY_STATE,
    NULL AS ESTABLISHMENT_ID,
    NULL AS ESTABLISHMENT_ADDRESS,
    NULL AS ESTABLISHMENT_POSTAL_CODE,
    NULL AS ESTABLISHMENT_COUNTRY_ID,
    NULL AS ESTABLISHMENT_PROVINCE_ID,
    NULL AS ESTABLISHMENT_LOCATION_ID,
    NULL AS ESTABLISHMENT_SITUATION_ID,
    NULL AS ESTABLISHMENT_STATE
FROM
    COMPANIES c

UNION ALL
SELECT
    'ESTABLECIMIENTO' AS TYPE,
    c.ID AS COMPANY_ID,
    c.NIF,
    c.NAME AS COMPANY_NAME,
    c.EMAIL AS COMPANY_EMAIL,
    c.PAGE_WEB AS COMPANY_PAGE_WEB,
    c.OBSERVATION AS COMPANY_OBSERVATION,
    c.ADDRESS AS COMPANY_ADDRESS,
    c.POSTAL_CODE AS COMPANY_POSTAL_CODE,
    c.COUNTRY_ID AS COMPANY_COUNTRY_ID,
    c.PROVINCE_ID AS COMPANY_PROVINCE_ID,
    c.LOCATION_ID AS COMPANY_LOCATION_ID,
    c.SITUATION_ID AS COMPANY_SITUATION_ID,
    c.STATE AS COMPANY_STATE,
    e.ID AS ESTABLISHMENT_ID,
    e.ADDRESS AS ESTABLISHMENT_ADDRESS,
    e.POSTAL_CODE AS ESTABLISHMENT_POSTAL_CODE,
    e.COUNTRY_ID AS ESTABLISHMENT_COUNTRY_ID,
    e.PROVINCE_ID AS ESTABLISHMENT_PROVINCE_ID,
    e.LOCATION_ID AS ESTABLISHMENT_LOCATION_ID,
    e.SITUATION_ID AS ESTABLISHMENT_SITUATION_ID,
    e.STATE AS ESTABLISHMENT_STATE
FROM
    COMPANIES c
RIGHT JOIN
    ESTABLISHMENTS e ON c.ID = e.COMPANY_ID;


CREATE TABLE TYPES_ACTUATIONS
(
    ID                      NUMBER(12) DEFAULT SEQ_TYPES_ACTUATIONS.nextval NOT NULL,
    TYPE                    VARCHAR2(20),
    NAME                    VARCHAR2(200),
    TYPE_INDUSTRY		    NUMBER(32),
    VISIBLE_CCAA            NUMBER,
    CREATED_BY              NUMBER(32),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);

ALTER TABLE TYPES_ACTUATIONS ADD CONSTRAINT PK_TYPES_ACTUATIONS__ID PRIMARY KEY (ID);



CREATE TABLE COMPANIES_ACTUATIONS
(
    ID           NUMBER(12) default SEQ_ESTABLISHMENTS.nextval NOT NULL,
    COMPANY_ID   NUMBER(12)                                    NOT NULL,
    ACTUATION_ID NUMBER(12)                                    NOT NULL,
    CREATED_BY   NUMBER(32),
    CREATED_AT   TIMESTAMP(6),
    UPDATED_BY   NUMBER(32),
    UPDATED_AT   TIMESTAMP(6),
    STATE        NUMBER(1)  DEFAULT 1                          NOT NULL
);
ALTER TABLE COMPANIES_ACTUATIONS ADD CONSTRAINT PK_COMPANIES_ACTUATIONS__ID PRIMARY KEY (ID);
ALTER TABLE COMPANIES_ACTUATIONS ADD CONSTRAINT FK_COMPANIES_ACTUATIONS__COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID);
ALTER TABLE COMPANIES_ACTUATIONS ADD CONSTRAINT FK_COMPANIES_ACTUATION_ID__COMPANY_ID FOREIGN KEY (ACTUATION_ID) REFERENCES TYPES_ACTUATIONS(ID);