INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (26, DATE '2010-05-12', null, 1, 'Comidas preparadas;Alimentos para Grupos Específicos;Complementos alimenticios;y otros ingredientes y productos alimenticios',0, 1, null, TIMESTAMP '1970-01-01 18:51:23');
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (27, DATE '2010-05-12', null, 1, 'Aguas envasadas y hielo', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (28, DATE '2010-02-22', null, 0, 'Helados.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (29, DATE '2010-02-22', null, 0, 'Bebidas no alcohólicas.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (15, DATE '2010-06-21', null, 0, 'Leche y derivados.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (16, DATE '2010-06-21', null, 0, 'Oleaginosas y grasas comestibles.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (20, DATE '2010-06-21', null, 0, 'Cereales, harinas y derivados', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (21, DATE '2010-06-21', null, 0, 'Vegetales (Hortalizas, Frutas, Setas, Tubérculos, Legumbres) y Derivados', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (23, DATE '2010-06-21', null, 0, 'Azúcares, derivados, miel y productos relacionados con la producción de miel', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (24, DATE '2010-06-21', null, 0, 'Condimentos y especias.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (25, DATE '2010-06-21', null, 0, 'Alimentos estimulantes, especies vegetales para infusiones y sus derivados.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (30, DATE '2010-06-21', null, 0, 'Bebidas alcohólicas.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (31, DATE '2010-06-21', null, 0, 'Ingredientes tecnológicos.', 0, 1, null, TIMESTAMP '2014-03-14 10:26:26');
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (39, DATE '2010-06-21', null, 0, 'Materiales y objetos destinados a entrar en contacto con los alimentos. ', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (40, DATE '2010-06-21', null, 0, 'Almacén, distribución, transporte, envasado e importación polivalente.', 0, 1, null, TIMESTAMP '2016-04-11 12:24:33');
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (5, DATE '2010-06-18', null, 0, 'Conservación de alimentos.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (10, DATE '2010-06-18', null, 0, 'Carnes y derivados, aves y caza.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (12, DATE '2010-06-18', null, 0, 'Pescado, crustáceos, moluscos y derivados.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (14, DATE '2010-06-18', null, 0, 'Huevos y derivados.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (17, DATE '2010-12-21', null, 0, 'Cereales.', 1, 0, null, TIMESTAMP '2017-06-02 11:16:45');
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (18, DATE '2010-12-21', null, 0, 'Leguminosas.', 1, 0, null, TIMESTAMP '2017-06-02 11:17:26');
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (19, DATE '2010-12-21', null, 0, 'Tubérculos.', 1, 0, null, TIMESTAMP '2017-06-02 11:17:52');
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (37, DATE '2010-12-16', null, 0, 'Detergentes, desinfectantes, sesinsectantes y otros productos para uso en la industria alimentaria', 1, 0, null, null);


INSERT INTO ACTIVITIES(code,NAME) VALUES ('02','Agua mineral natural');
INSERT INTO ACTIVITIES(code,NAME) VALUES ('03','Agua de manantial');
INSERT INTO ACTIVITIES(code,NAME) VALUES ('04','Agua potable preparada');
INSERT INTO ACTIVITIES(code,NAME) VALUES ('06','Agua de abastecimiento público preparada');


INSERT INTO ACTIVITIES_KEYS(KEY_ID, ACTIVITY_ID)
VALUES (27,130,)
