INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (26, DATE '2010-05-12', null, 1, 'Comidas preparadas;Alimentos para Grupos Específicos;Complementos alimenticios;y otros ingredientes y productos alimenticios',0, 1, null, TIMESTAMP '1970-01-01 18:51:23');
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (27, DATE '2010-05-12', null, 1, 'Aguas envasadas y hielo', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (28, DATE '2010-02-22', null, 0, 'Helados.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (29, DATE '2010-02-22', null, 0, 'Bebidas no alcohólicas.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (15, DATE '2010-06-21', null, 0, 'Leche y derivados.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (16, DATE '2010-06-21', null, 0, 'Oleaginosas y grasas comestibles.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (20, DATE '2010-06-21', null, 0, 'Cereales, harinas y derivados', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (21, DATE '2010-06-21', null, 0, 'Vegetales (Hortalizas, Frutas, Setas, Tubérculos, Legumbres) y Derivados', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (23, DATE '2010-06-21', null, 0, 'Azúcares, derivados, miel y productos relacionados con la producción de miel', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (24, DATE '2010-06-21', null, 0, 'Condimentos y especias.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (25, DATE '2010-06-21', null, 0, 'Alimentos estimulantes, especies vegetales para infusiones y sus derivados.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (30, DATE '2010-06-21', null, 0, 'Bebidas alcohólicas.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (31, DATE '2010-06-21', null, 0, 'Ingredientes tecnológicos.', 0, 1, null, TIMESTAMP '2014-03-14 10:26:26');
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (39, DATE '2010-06-21', null, 0, 'Materiales y objetos destinados a entrar en contacto con los alimentos. ', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (40, DATE '2010-06-21', null, 0, 'Almacén, distribución, transporte, envasado e importación polivalente.', 0, 1, null, TIMESTAMP '2016-04-11 12:24:33');
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (5, DATE '2010-06-18', null, 0, 'Conservación de alimentos.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (10, DATE '2010-06-18', null, 0, 'Carnes y derivados, aves y caza.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (12, DATE '2010-06-18', null, 0, 'Pescado, crustáceos, moluscos y derivados.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (14, DATE '2010-06-18', null, 0, 'Huevos y derivados.', 0, 1, null, null);
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (17, DATE '2010-12-21', null, 0, 'Cereales.', 1, 0, null, TIMESTAMP '2017-06-02 11:16:45');
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (18, DATE '2010-12-21', null, 0, 'Leguminosas.', 1, 0, null, TIMESTAMP '2017-06-02 11:17:26');
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (19, DATE '2010-12-21', null, 0, 'Tubérculos.', 1, 0, null, TIMESTAMP '2017-06-02 11:17:52');
INSERT INTO KEYS (ID, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, NAME, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT)
VALUES (37, DATE '2010-12-16', null, 0, 'Detergentes, desinfectantes, sesinsectantes y otros productos para uso en la industria alimentaria', 1, 0, null, null);


INSERT INTO ACTIVITIES(id,code,NAME) VALUES (1,'02','Agua mineral natural');
INSERT INTO ACTIVITIES(id,code,NAME) VALUES (2,'03','Agua de manantial');
INSERT INTO ACTIVITIES(id,code,NAME) VALUES (3,'04','Agua potable preparada');
INSERT INTO ACTIVITIES(id,code,NAME) VALUES (4,'06','Agua de abastecimiento público preparada');

INSERT INTO SUB_ACTIVITIES(id,NAME) VALUES (1,'02','Agua mineral natural');
INSERT INTO SUB_ACTIVITIES(id,NAME) VALUES (2,'03','Agua de manantial');


INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (5, 'Número Nulo', 1, null, null, 0, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (1, 'Alta', 1, null, null, 1, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (2, 'Baja', 1, null, null, 1, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (8, 'En Trámite (*)', 1, null, null, 1, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (13, 'Notificado',  1, null, null, 1, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (14, 'Se ajusta a la legislación vigente',  0, null, null, 1, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (9, 'Alta (*)', 0, null, null, 1, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (11, 'Baja (*)', 0, null, null, 1, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (12, 'Número Nulo', 0, null, TIMESTAMP '2015-04-08 12:26:25', null, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (15, 'No se ajusta a la legislación vigente', 0, null, null, 0, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (16, 'Reconocimiento mutuo', 0, null, null, 0, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (17, 'Cese comercialización', 0, null, null, 0, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (7, 'Pendiente', 1, null, null, 1, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (6, 'Suspensión temporal', 1, null, null, 0, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (20, 'Final de Existencias', null, null, null, 0, 0, 0);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (21, 'SIN NOTIFICAR A LAS AACC', 1, null, TIMESTAMP '2019-06-14 13:51:47', null, 0, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (22, 'Alta Condicional',  1, null, TIMESTAMP '1970-01-01 15:02:20', null, 1, 1);


INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (0, 'NIN', 'Ninguno', 1, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (1, 'ES', 'España', 1, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (2, 'DE', 'Alemania', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (3, 'FR', 'Francia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (4, 'UE', 'Fuera de la Unión Europea', 1, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (5, 'BE', 'Bélgica', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (6, 'BG', 'Bulgaria', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (7, 'DK', 'Dinamarca', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (8, 'FI', 'Finlandia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (9, 'GA', 'Grecia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (10, 'NL', 'Países Bajos', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (11, 'HN', 'Hungría', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (12, 'IE', 'Irlanda', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (13, 'IT', 'Italia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (14, 'LX', 'Luxemburgo', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (15, 'PL', 'Polonia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (16, 'PT', 'Portugal', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (17, 'UK', 'Reino Unido', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (18, 'CY', 'Chipre', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (19, 'SI', 'Eslovenia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (20, 'EE', 'Estonia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (21, 'LV', 'Letonia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (22, 'LT', 'Lituania', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (23, 'MT', 'Malta', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (24, 'CZ', 'República Checa', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (25, 'SK', 'República Eslovaca', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (26, 'RO', 'Rumanía', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (27, 'SU', 'Suecia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (28, 'AT', 'Austria', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (100, 'UE', 'Fabricado en la UE', 1, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (101, 'NP', 'No figura País', 1, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (102, 'HR', 'Croacia', 0, null, null);


