-- TABLA KEYS
INSERT INTO KEYS
(ID, NAME, DATE_REGISTER, DATE_UNREGISTER, ALLOW_PRODUCT, IS_OLD, IS_PUBLIC, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(1, 'Clave 40: ALMACEN, DISTRIBUCIÓN, TRANSPORTE, ENVASADO E IMPORTACIÓN POLIVALENTE', TIMESTAMP '2017-08-09 00:00:00.000000', NULL, 1, 0, 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);

-- TABLA ACTIVITIES
INSERT INTO ACTIVITIES
(ID, CODE, NAME, IS_PUBLIC, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(1, '02', 'Polivalente', 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES
(ID, CODE, NAME, IS_PUBLIC, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(2, '03', 'Mercado mayorista (INDICAR SECTOR/ES)', 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES
(ID, CODE, NAME, IS_PUBLIC, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(3, '04', 'Envasador de productos de origen
animal (INDICAR SECTOR)', 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES
(ID, CODE, NAME, IS_PUBLIC, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(4, '05', 'Transporte de productos alimenticios y alimentarios a temperatura regulada (salvo alimentos granulados, líquidos o en polvo, a granel)', 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES
(ID, CODE, NAME, IS_PUBLIC, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(5, '06', 'Transporte de productos alimenticios y alimentarios, sin control de temperatura (salvo alimentos granulados, líquidos o en polvo, a granel)', 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES
(ID, CODE, NAME, IS_PUBLIC, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(6, '07', 'Transporte sin control de temperatura de productos alimenticios granulados, líquidos o en polvo, a granel.', 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES
(ID, CODE, NAME, IS_PUBLIC, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(7, '08', 'Transporte a temperatura regulada de productos alimenticios granulados, líquidos o en polvo, a granel.', 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES
(ID, CODE, NAME, IS_PUBLIC, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(8, '09', 'Establecimiento de congelación de
POAS', 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES
(ID, CODE, NAME, IS_PUBLIC, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(9, '10', 'Establecimiento de congelación de productos alimenticios distintos de POAS', 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES
(ID, CODE, NAME, IS_PUBLIC, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(10, '11', 'Buque de almacenamiento en congelación', 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES
(ID, CODE, NAME, IS_PUBLIC, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(11, '97', 'Frigorífico de productos de origen animal (INDICAR SECTOR)', 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES
(ID, CODE, NAME, IS_PUBLIC, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(12, '98', 'En congelación de productos de origen animal (INDICAR SECTOR)', 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);

-- TABLA CATEGORIES
INSERT INTO CATEGORIES
(ID, NAME, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(1, 'Envasado. (nunca PRODUCTOS DE ORIGEN ANIMAL)', 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO CATEGORIES
(ID, NAME, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(2, 'Distribución', 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO CATEGORIES
(ID, NAME, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(3, 'Almacenamiento', 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO CATEGORIES
(ID, NAME, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(4, 'Importación', 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO CATEGORIES
(ID, NAME, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(5, 'Actividades específicas no recogidas en las categorías anteriores', 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);



-- TABLA SUB_ACTIVITIES
INSERT INTO SUB_ACTIVITIES
(ID, NAME, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(1, 'Sector cárnico', 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO SUB_ACTIVITIES
(ID, NAME, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(2, 'Sector de la pesca', 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO SUB_ACTIVITIES
(ID, NAME, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(3, 'Sector lácteo', 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO SUB_ACTIVITIES
(ID, NAME, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(4, 'Sector huevos', 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO SUB_ACTIVITIES
(ID, NAME, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(5, 'Sector comidas preparadas a base de POAS.', 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);




-- TABLA ACTIVITIES_KEYS
INSERT INTO ACTIVITIES_KEYS
(ID, KEY_ID, ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(1, 1, 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS
(ID, KEY_ID, ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(2, 1, 2, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS
(ID, KEY_ID, ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(3, 1, 3, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS
(ID, KEY_ID, ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(4, 1, 4, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS
(ID, KEY_ID, ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(5, 1, 5, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS
(ID, KEY_ID, ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(6, 1, 6, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS
(ID, KEY_ID, ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(7, 1, 7, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS
(ID, KEY_ID, ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(8, 1, 8, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS
(ID, KEY_ID, ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(9, 1, 9, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS
(ID, KEY_ID, ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(10, 1, 10, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS
(ID, KEY_ID, ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(11, 1, 11, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS
(ID, KEY_ID, ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(12, 1, 12, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);

-- TABLA ACTIVITIES_KEYS_CATEGORIES
INSERT INTO ACTIVITIES_KEYS_CATEGORIES
(ID, ACTIVITY_KEY_ID, CATEGORY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(1, 1, 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES
(ID, ACTIVITY_KEY_ID, CATEGORY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(2, 1, 2, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES
(ID, ACTIVITY_KEY_ID, CATEGORY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(3, 1, 3, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES
(ID, ACTIVITY_KEY_ID, CATEGORY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(4, 1, 4, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES
(ID, ACTIVITY_KEY_ID, CATEGORY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(5, 2, 5, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES
(ID, ACTIVITY_KEY_ID, CATEGORY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(6, 3, 5, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES
(ID, ACTIVITY_KEY_ID, CATEGORY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(7, 4, 5, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES
(ID, ACTIVITY_KEY_ID, CATEGORY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(8, 5, 5, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES
(ID, ACTIVITY_KEY_ID, CATEGORY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(9, 6, 5, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES
(ID, ACTIVITY_KEY_ID, CATEGORY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(10, 7, 5, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES
(ID, ACTIVITY_KEY_ID, CATEGORY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(11, 8, 5, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES
(ID, ACTIVITY_KEY_ID, CATEGORY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(12, 9, 5, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES
(ID, ACTIVITY_KEY_ID, CATEGORY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(13, 10, 5, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES
(ID, ACTIVITY_KEY_ID, CATEGORY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(14, 11, 3, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES
(ID, ACTIVITY_KEY_ID, CATEGORY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(15, 12, 3, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);



-- TABLA ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(1, 6, 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(2, 6, 2, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(3, 6, 3, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(4, 6, 4, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(5, 6, 5, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(6, 8, 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(7, 8, 2, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(8, 8, 3, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(9, 8, 4, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(10, 8, 5, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(11, 11, 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(12, 11, 2, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(13, 11, 3, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(14, 11, 4, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(15, 11, 5, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(16, 12, 1, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(17, 12, 2, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(18, 12, 3, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(19, 12, 4, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);
INSERT INTO ACTIVITIES_KEYS_CATEGORIES_SUB_ACTIVITIES
(ID, ACTIVITY_KEY_CATEGORY_ID, SUB_ACTIVITY_ID, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, STATE)
VALUES(20, 12, 5, 1, TIMESTAMP '2017-08-09 00:00:00.000000', NULL, NULL, 1);


INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (5, 'Número Nulo', 1, null, null, 0, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (1, 'Alta', 1, null, null, 1, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (2, 'Baja', 1, null, null, 1, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (8, 'En Trámite (*)', 1, null, null, 1, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (13, 'Notificado',  1, null, null, 1, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (14, 'Se ajusta a la legislación vigente',  0, null, null, 1, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (9, 'Alta (*)', 0, null, null, 1, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (11, 'Baja (*)', 0, null, null, 1, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (12, 'Número Nulo', 0, null, TIMESTAMP '2015-04-08 12:26:25', null, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (15, 'No se ajusta a la legislación vigente', 0, null, null, 0, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (16, 'Reconocimiento mutuo', 0, null, null, 0, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (17, 'Cese comercialización', 0, null, null, 0, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (7, 'Pendiente', 1, null, null, 1, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (6, 'Suspensión temporal', 1, null, null, 0, 1, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (20, 'Final de Existencias', null, null, null, 0, 0, 0);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (21, 'SIN NOTIFICAR A LAS AACC', 1, null, TIMESTAMP '2019-06-14 13:51:47', null, 0, 1);
INSERT INTO SITUATIONS (ID, NAME, NEW_OPTION, CREATED_BY, CREATED_AT, NO_DELETE, VISIBLE_RGSA, VISIBLE_UE)
VALUES (22, 'Alta Condicional',  1, null, TIMESTAMP '1970-01-01 15:02:20', null, 1, 1);


INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (0, 'NIN', 'Ninguno', 1, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (1, 'ES', 'España', 1, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (2, 'DE', 'Alemania', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (3, 'FR', 'Francia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (4, 'UE', 'Fuera de la Unión Europea', 1, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (5, 'BE', 'Bélgica', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (6, 'BG', 'Bulgaria', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (7, 'DK', 'Dinamarca', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (8, 'FI', 'Finlandia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (9, 'GA', 'Grecia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (10, 'NL', 'Países Bajos', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (11, 'HN', 'Hungría', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (12, 'IE', 'Irlanda', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (13, 'IT', 'Italia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (14, 'LX', 'Luxemburgo', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (15, 'PL', 'Polonia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (16, 'PT', 'Portugal', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (17, 'UK', 'Reino Unido', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (18, 'CY', 'Chipre', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (19, 'SI', 'Eslovenia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (20, 'EE', 'Estonia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (21, 'LV', 'Letonia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (22, 'LT', 'Lituania', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (23, 'MT', 'Malta', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (24, 'CZ', 'República Checa', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (25, 'SK', 'República Eslovaca', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (26, 'RO', 'Rumanía', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (27, 'SU', 'Suecia', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (28, 'AT', 'Austria', 0, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (100, 'UE', 'Fabricado en la UE', 1, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (101, 'NP', 'No figura País', 1, null, null);
INSERT INTO COUNTRIES (ID, ENROLLMENT,NAME, NO_DELETE, CREATED_BY, CREATED_AT)
VALUES (102, 'HR', 'Croacia', 0, null, null);


INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (1, 'IMPI', 'Impreso CIUDADANO', 0, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (2, 'DAII', 'Doc adjunto a impreso', 0, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (3, 'RAPOASI', 'Resolución de Autorización POAS (CCAA)', 0, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (4, 'RCCAAI', 'Resolución (CCAA)', 0, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (5, 'DII', 'Doc de inscripción (AESAN) -modelos-', 0, 0, 1);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (6, 'CAESANI', 'Certificado (AESAN) -modelos-', 0, 0, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (7, 'OFI', 'Otros Ficheros', 0, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (8, 'DEEMMI', 'Docs de otros EEMM', 0, 0, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (9, 'TASAI', 'Tasas', 0, 1, 1);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (21, 'IMPP', 'Impreso CIUDADANO', 1, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (22, 'EP', 'Etiqueta', 1, 1, 1);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (23, 'ODAIP', 'Doc adjunto a impreso', 1, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (24, 'ITP', 'Informe Tecnico (autoridad competente)', 1, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (25, 'RAC', 'Resolucion Autoridad Competente', 1, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (26, 'CACP', 'Certificado (AESAN) -modelos-', 1, 0, 1);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (27, 'OFP', 'Otros Ficheros', 1, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (28, 'AP', 'BOE AG', 1, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (29, 'DEEMMP', 'Docs de otros EEMM', 1, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (30, 'TASAP', 'Tasas', 1, 0, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (31, 'ENMAS', 'Envio Masivo', null, null, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (32, 'DIDT', 'Doc. Producto Firma AECOSAN', 1, 0, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (33, 'DROK', 'Doc modificacion OK -modelo-', 1, 0, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (34, 'MIGIND', 'Migración Documentación Industrias', 0, 0, 1);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (35, 'MIGPRO', 'Migración Documentación Productos', 1, 0, 1);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (37, 'VALAC', 'Valoración Autoridad Competente', 1, 1, 1);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (38, 'acuse de recibo', 'Acuse de recibo', 1, 1, 0);


INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (1, 'Solicitud de Inscripción', 1, 1);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (2, 'Adjudicación de número (AECOSAN)', 0, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (3, 'Cambio Razón Social', 1, 1);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (4, 'Cambio de domicilio', 1, 1);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (5, 'Ampliación/ baja actividades', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (6, 'Baja de la Industria', 1, 1);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (7, 'Convalidación', 1, 1);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (8, 'Emisión Certificados', 0, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (9, 'Cambio de oficio', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (10, 'Otras gestiones', 1, 1);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (11, 'Reagrupacion producto', 0, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (21, 'Solicitud de Inscripción / NOTIFICACIÓN', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (22, 'Cambio Etiqueta: Empresa Responsable', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (23, 'Cambio Etiqueta: Nombre Comercial', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (24, 'Cambio Etiqueta: Composición', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (25, 'Cambio Etiqueta: Diseño u otras razones', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (26, 'Otras Modificaciones', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (27, 'Baja / Cese Comercialización', 1, 1);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (28, 'Emisión Certificados', 0, 1);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (29, 'Cambio de oficio', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (30, 'Otras gestiones', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (31, 'Suspensión completa', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (32, 'Suspensión de actividades', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (33, 'Reinicio de actividades', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (34, 'Reapertura', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (35, 'Revisión datos firma', 0, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (36, 'Revisión datos firma', 0, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (37, 'Etiqueta migrada', 0, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (38, 'Suministrador para Piensos', 0, 1);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (39, 'Modificacion manual del NUE', 0, 1);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (40, 'Etiqueta adicional', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (41, 'Etiqueta adicional', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (50, 'Producto retirado', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (51, 'Trámite financiación', 1, 0);
INSERT INTO TYPES_ACTIONS (ID, NAME, VISIBLE_CCAA, NO_DELETE) VALUES (52, 'Tasas', 0, 0);


INSERT INTO AUTHORIZATIONS (ID, NAME) VALUES (1, 'Mataderos NO RUMIANTES (hemoderivados) (anexo IV, cap IV, secc C, a), 1ºpárr R(CE) 999/2001)');
INSERT INTO AUTHORIZATIONS (ID, NAME) VALUES (2, 'Mataderos PORCINO y RUMIANTES, autorizados (hemoderivados) (anexo IV, cap IV, secc C, a), 2º, 3º,4ºpárr. R(CE) 999/2001)');
INSERT INTO AUTHORIZATIONS (ID, NAME) VALUES (3, 'Mataderos, salas de despiece, establecimientos - NO RUMIANTES (PATs) (anexo IV, cap IV, secc D, a) 1ºpárr. R(CE) 999/2001)');
INSERT INTO AUTHORIZATIONS (ID, NAME) VALUES (4, 'Mataderos, salas de despiece, establecimientos - RUMIANTES, autorizados (PATs) (anexo IV, cap IV, secc D, a), 2º,3º, 4ºpárr. R(CE) 999/2001)');
INSERT INTO AUTHORIZATIONS (ID, NAME) VALUES (5, 'Suministrador de materias primas para piensos (R(CE) nº 183/2005)');



INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY) VALUES (1, 'R_USERS', DATE '2023-11-01', DATE '2023-11-01', 1, 1);
INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY) VALUES (2, 'X_USERS', DATE '2023-11-01', DATE '2023-11-01', 2, 2);
INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY) VALUES (3, 'R_PROFILES', DATE '2023-11-01', DATE '2023-11-01', 1, 1);
INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY) VALUES (4, 'X_PROFILES', DATE '2023-11-01', DATE '2023-11-01', 2, 2);
INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY) VALUES (5, 'R_ENTITIES', DATE '2023-11-01', DATE '2023-11-01', 1, 1);
INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY) VALUES (6, 'X_ENTITIES', DATE '2023-11-01', DATE '2023-11-01', 1, 1);
INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY) VALUES (7, 'R_PRODUCT', DATE '2023-11-01', DATE '2023-11-01', 1, 1);
INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY) VALUES (8, 'X_PRODUCT', DATE '2023-11-01', DATE '2023-11-01', 1, 1);
INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY) VALUES (9, 'R_INDUSTRY', DATE '2023-11-01', DATE '2023-11-01', 1, 1);
INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY) VALUES (10, 'X_INDUSTRY',DATE '2023-11-01', DATE '2023-11-01', 1, 1);
INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY) VALUES (11, 'R_LIST', DATE '2023-11-01', DATE '2023-11-01', 1, 1);
INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY) VALUES (12, 'X_LIST', DATE '2023-11-01', DATE '2023-11-01', 1, 1);
