CREATE TABLE TYPES_ACTUATIONS
(
    ID                      NUMBER(12) DEFAULT SEQ_TYPES_DOCUMENTS.nextval NOT NULL,
    TYPE                    VARCHAR2(20),
    NAME                    VARCHAR2(200),
    TYPE_INDUSTRY		    NUMBER(32),
    VISIBLE_CCAA            NUMBER,
    CREATED_BY              NUMBER(32),
    CREATED_AT              TIMESTAMP(6),
    UPDATED_BY              NUMBER(32),
    UPDATED_AT              TIMESTAMP(6),
    STATE                   NUMBER(1) DEFAULT 1 NOT NULL
);

ALTER TABLE TYPES_ACTUATIONS ADD CONSTRAINT PK_TYPES_ACTUATIONS__ID PRIMARY KEY (ID);

ACTUATIONS_COMPANIES

ACTUATIONS_PRODUCTS