
INSERT INTO USERS (ID, NIF, NAME, FIRST_SURNAME,SECOND_SURNAME, PHONE, EMAIL, STATE) VALUES (0, '99999018D', 'CIUDADANO', 'ACTIVO', 'FICTICIO', '611123123', 'RGSEAA@aesan.gob.es', 1);
INSERT INTO USERS (ID, NIF, NAME, FIRST_SURNAME,SECOND_SURNAME, PHONE, EMAIL, STATE) VALUES (SEQ_USERS.NEXTVAL, '00000000T', 'RGSEAA', 'SYSTEM', null, '611123123', 'RGSEAA@aesan.gob.es', 1);
INSERT INTO USERS (ID, NIF, NAME, FIRST_SURNAME,SECOND_SURNAME, PHONE, EMAIL, STATE) VALUES (SEQ_USERS.NEXTVAL, '75167143S', 'Alejandro', 'Jiménez', 'González', '611123123', 'ajimenez@serikat.es', 1);

INSERT INTO PROFILES(ID, NAME, STATE) VALUES (SEQ_PROFILES.NEXTVAL,'Administrador de RGSEAA', 1);
INSERT INTO PROFILES(ID, NAME, STATE) VALUES (SEQ_PROFILES.NEXTVAL,'Administrador de ámbito', 1);

/*
INSERT INTO ENTITIES_TYPES (ID, STATE, NAME, DESCRIPTION) VALUES  (SEQ_ENTITIES_TYPES.NEXTVAL, 1, 'Entidad pública', 'Agencia de la administración pública', DATE '2023-11-01', DATE '2023-01-10', 1, 1);
INSERT INTO ENTITIES_TYPES (ID, STATE, NAME, DESCRIPTION) VALUES  (SEQ_ENTITIES_TYPES.NEXTVAL, 1, 'Comunidad autónoma', 'Unidad administrativa');

INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Agencia española de seguridad alimentaria y nutrición', 'Agencia española de seguridad alimentaria y nutrición', 'AESAN', 1, '28000', 'C/ Alcalá 56', 'Administrador RGSEAA', '012345679', 'soporte_RGSEAA@aesan.gob.es', 1, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Andalucía', 'Andalucía','AND', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '622622622', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Aragón', 'Aragón','ARA', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1, DATE '2022-06-01', DATE '2023-01-17', 1, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Asturias, Principado de', 'Asturias, Principado de','AST', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Baleares, Islas', 'Baleares, Islas','BAL', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Canarias', 'Canarias','CAN', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Cantabria', 'Cantabria','CNT', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Castilla y León', 'Castilla y León','CYL', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Castilla - La Mancha', 'Castilla - La Mancha','CLM', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Cataluña', 'Cataluña','CAT', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Valenciana Comunidad', 'Valenciana Comunidad','VAL', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Extremadura', 'Extremadura','EXT', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Galicia', 'Galicia', 'GAL', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Madrid, Comunidad de', 'Madrid, Comunidad de', 'MAD', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Murcia, Región de', 'Murcia, Región de','MUR', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Navarra, Comunidad Foral de', 'Navarra, Comunidad Foral de','NAV', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'País Vasco', 'País Vasco','EUS', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Rioja, La', 'Rioja, La','RIO', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Ceuta', 'Ceuta','CEU', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);
INSERT INTO ENTITIES (ID, NAME, DESCRIPTION, CODE, TYPE_ID, POSTAL_CODE, ADDRESS, CONTACT_PERSON, PHONE, EMAIL, ROOT_ENTITY, STATE) VALUES  (SEQ_ENTITIES.NEXTVAL, 'Melilla', 'Melilla','MEL', 2, 'S/N', 'S/N', 'Administrador RGSEAA', '612123123', 'soporte_RGSEAA@aesan.gob.es', 0, 1);

INSERT INTO MODULES_TYPES (ID, STATE, NAME, DESCRIPTION) VALUES (SEQ_MODULES_TYPES.NEXTVAL, 1, 'Module-type 1', 'Ejemplo module-type 1');
INSERT INTO MODULES_TYPES (ID, STATE, NAME, DESCRIPTION) VALUES (SEQ_MODULES_TYPES.NEXTVAL, 1, 'Module-type 2', 'Ejemplo module-type 2');
INSERT INTO MODULES_TYPES (ID, STATE, NAME, DESCRIPTION) VALUES (SEQ_MODULES_TYPES.NEXTVAL, 1, 'Module-type 3', 'Ejemplo module-type 3');

INSERT INTO MODULES (ID, TYPE_ID, STATE, CODE) VALUES (SEQ_MODULES.NEXTVAL, 1, 1, 'EMPR');
INSERT INTO MODULES (ID, TYPE_ID, STATE, CODE) VALUES (SEQ_MODULES.NEXTVAL, 1, 1, 'FIRM');

INSERT INTO USERS_MODULES(ID, STATE, MODULE_ID, USER_ID) VALUES (SEQ_USERS_MODULES.NEXTVAL, 1, 1, 1);
INSERT INTO USERS_MODULES(ID, STATE, MODULE_ID, USER_ID) VALUES (SEQ_USERS_MODULES.NEXTVAL, 1, 2, 1);

INSERT INTO USERS_ENTITIES(ID, ENTITY_ID, USER_ID, STATE, SCOPE_CODE) VALUES (SEQ_USERS_ENTITIES.NEXTVAL,1,1,1,'#1#2#');
INSERT INTO USERS_ENTITIES(ID, ENTITY_ID, USER_ID, STATE, SCOPE_CODE) VALUES (SEQ_USERS_ENTITIES.NEXTVAL,2,1,1,'#2#2#');
*/

INSERT INTO USERS_PROFILES(ID, STATE, PROFILE_ID, USER_ID) VALUES (0, 1, 1, 1);
INSERT INTO USERS_PROFILES(ID, STATE, PROFILE_ID, USER_ID) VALUES (SEQ_USERS_PROFILES.NEXTVAL, 1, 1, 2);
INSERT INTO USERS_PROFILES(ID, STATE, PROFILE_ID, USER_ID) VALUES (SEQ_USERS_PROFILES.NEXTVAL, 1, 2, 1);

INSERT INTO PERMISSIONS (ID, CODE, NAME, STATE) VALUES (SEQ_PERMISSIONS.NEXTVAL, 'R_USERS', 'Permiso de lectura del módulo usuarios', 1);
INSERT INTO PERMISSIONS (ID, CODE, NAME, STATE) VALUES (SEQ_PERMISSIONS.NEXTVAL, 'X_USERS', 'Permiso de escritura del módulo usuarios', 1);
INSERT INTO PERMISSIONS (ID, CODE, NAME, STATE) VALUES (SEQ_PERMISSIONS.NEXTVAL, 'R_PROFILES','Permiso de lectura del módulo perfiles', 1);
INSERT INTO PERMISSIONS (ID, CODE, NAME, STATE) VALUES (SEQ_PERMISSIONS.NEXTVAL, 'X_PROFILES','Permiso de escritura del módulo perfiles', 1);
INSERT INTO PERMISSIONS (ID, CODE, NAME, STATE) VALUES (SEQ_PERMISSIONS.NEXTVAL, 'R_ENTITIES','Permiso de lectura del módulo entidades', 1);
INSERT INTO PERMISSIONS (ID, CODE, NAME, STATE) VALUES (SEQ_PERMISSIONS.NEXTVAL, 'X_ENTITIES','Permiso de escritura del módulo entidades', 1);
INSERT INTO PERMISSIONS (ID, CODE, NAME, STATE) VALUES (SEQ_PERMISSIONS.NEXTVAL, 'R_PRODUCT','Permiso de lectura del módulo productos', 1);
INSERT INTO PERMISSIONS (ID, CODE, NAME, STATE) VALUES (SEQ_PERMISSIONS.NEXTVAL, 'X_PRODUCT','Permiso de escritura del módulo productos', 1);
INSERT INTO PERMISSIONS (ID, CODE, NAME, STATE) VALUES (SEQ_PERMISSIONS.NEXTVAL, 'R_INDUSTRY','Permiso de lectura del módulo industria', 1);
INSERT INTO PERMISSIONS (ID, CODE, NAME, STATE) VALUES (SEQ_PERMISSIONS.NEXTVAL, 'X_INDUSTRY','Permiso de escritura del módulo industria', 1);
INSERT INTO PERMISSIONS (ID, CODE, NAME, STATE) VALUES (SEQ_PERMISSIONS.NEXTVAL, 'R_LIST','Permiso de lectura del módulo listado', 1);
INSERT INTO PERMISSIONS (ID, CODE, NAME, STATE) VALUES (SEQ_PERMISSIONS.NEXTVAL, 'X_LIST','Permiso de escritura del módulo listado', 1);


INSERT INTO PROFILES_PERMISSIONS (ID, STATE, PERMISSION_ID, PROFILE_ID) VALUES (SEQ_PROFILES_PERMISSIONS.NEXTVAL, 1, 1, 1);
INSERT INTO PROFILES_PERMISSIONS (ID, STATE, PERMISSION_ID, PROFILE_ID) VALUES (SEQ_PROFILES_PERMISSIONS.NEXTVAL, 1, 2, 1);
INSERT INTO PROFILES_PERMISSIONS (ID, STATE, PERMISSION_ID, PROFILE_ID) VALUES (SEQ_PROFILES_PERMISSIONS.NEXTVAL, 1, 3, 1);
INSERT INTO PROFILES_PERMISSIONS (ID, STATE, PERMISSION_ID, PROFILE_ID) VALUES (SEQ_PROFILES_PERMISSIONS.NEXTVAL, 1, 4, 1);
INSERT INTO PROFILES_PERMISSIONS (ID, STATE, PERMISSION_ID, PROFILE_ID) VALUES (SEQ_PROFILES_PERMISSIONS.NEXTVAL, 1, 5, 1);
INSERT INTO PROFILES_PERMISSIONS (ID, STATE, PERMISSION_ID, PROFILE_ID) VALUES (SEQ_PROFILES_PERMISSIONS.NEXTVAL, 1, 6, 1);


-- TABLE TYPES_ACTUATIONS
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (11, 'Reagrupacion producto', 1, 0);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (40, 'Etiqueta adicional', 0, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (41, 'Etiqueta adicional', 1, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (51, 'Trámite financiación', 1, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (37, 'Etiqueta migrada', 1, 0);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (38, 'Suministrador para Piensos', 0, 0);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (1, 'Solicitud de Inscripción', 0, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (2, 'Adjudicación de número (AECOSAN)', 0, 0);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (3, 'Cambio Razón Social', 0, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (4, 'Cambio de domicilio', 0, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (5, 'Ampliación/ baja actividades', 0, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (6, 'Baja de la Industria', 0, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (7, 'Convalidación', 0, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (8, 'Emisión Certificados', 0, 0);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (9, 'Cambio de oficio', 0, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (10, 'Otras gestiones', 0, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (21, 'Solicitud de Inscripción / NOTIFICACIÓN', 1, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (22, 'Cambio Etiqueta: Empresa Responsable', 1, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (23, 'Cambio Etiqueta: Nombre Comercial', 1, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (24, 'Cambio Etiqueta: Composición', 1, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (25, 'Cambio Etiqueta: Diseño u otras razones', 1, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (26, 'Otras Modificaciones', 1, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (27, 'Baja / Cese Comercialización', 1, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (28, 'Emisión Certificados', 1, 0);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (29, 'Cambio de oficio', 1, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (30, 'Otras gestiones', 1, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (33, 'Reinicio de actividades', 0, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (34, 'Reapertura', 0, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (35, 'Revisión datos firma', 0, 0);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (36, 'Revisión datos firma', 1, 0);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (31, 'Suspensión completa', 0, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (32, 'Suspensión de actividades', 0, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (39, 'Modificacion manual del NUE', 0, 0);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (50, 'Producto retirado', 1, 1);
INSERT INTO TYPES_ACTUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA) VALUES (52, 'Tasas', 1, 0);

-- TABLE SITUATIONS
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (1, 'Alta', 0);
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (2, 'Baja', 0);
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (5, 'Número nulo', 0);
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (6, 'Suspensión temporal', 0);
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (7, 'Pendiente', 0);
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (8, 'En trámite (*)', 1);
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (9, 'Alta (*)', 1);
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (11, 'Baja (*)', 1);
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (12, 'Número nulo', 1);
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (13, 'Notificado', 1);
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (14, 'Se ajusta a la legislación vigente', 1);
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (15, 'No se ajusta a la legislación vigente', 1);
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (16, 'Reconocimiento mutuo', 1);
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (17, 'Cese comercialización', 1);
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (20, 'Final de existencias', 1);
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (21, 'SIN NOTIFICAR A LAS AACC', 1);
INSERT INTO SITUATIONS (ID, NAME, TYPE_COMPANY_PRODUCT) VALUES (22, 'Alta condicional', 0);

INSERT INTO AUTHORIZATIONS (ID, NAME) VALUES (1, 'Mataderos NO RUMIANTES (hemoderivados) (anexo IV, cap IV, secc C, a), 1ºpárr R(CE) 999/2001)');
INSERT INTO AUTHORIZATIONS (ID, NAME) VALUES (2, 'Mataderos PORCINO y RUMIANTES, autorizados (hemoderivados) (anexo IV, cap IV, secc C, a), 2º, 3º,4ºpárr. R(CE) 999/2001)');
INSERT INTO AUTHORIZATIONS (ID, NAME) VALUES (3, 'Mataderos, salas de despiece, establecimientos - NO RUMIANTES (PATs) (anexo IV, cap IV, secc D, a) 1ºpárr. R(CE) 999/2001)');
INSERT INTO AUTHORIZATIONS (ID, NAME) VALUES (4, 'Mataderos, salas de despiece, establecimientos - RUMIANTES, autorizados (PATs) (anexo IV, cap IV, secc D, a), 2º,3º, 4ºpárr. R(CE) 999/2001)');
INSERT INTO AUTHORIZATIONS (ID, NAME) VALUES (5, 'Suministrador de materias primas para piensos (R(CE) nº 183/2005)');

INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (1, 'IMPI', 'Impreso CIUDADANO', 0, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (2, 'DAII', 'Doc adjunto a impreso', 0, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (3, 'RAPOASI', 'Resolución de Autorización POAS (CCAA)', 0, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (4, 'RCCAAI', 'Resolución (CCAA)', 0, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (5, 'DII', 'Doc de inscripción (AESAN) -modelos-', 0, 0, 1);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (6, 'CAESANI', 'Certificado (AESAN) -modelos-', 0, 0, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (7, 'OFI', 'Otros Ficheros', 0, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (8, 'DEEMMI', 'Docs de otros EEMM', 0, 0, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (9, 'TASAI', 'Tasas', 0, 1, 1);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (21, 'IMPP', 'Impreso CIUDADANO', 1, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (22, 'EP', 'Etiqueta', 1, 1, 1);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (23, 'ODAIP', 'Doc adjunto a impreso', 1, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (24, 'ITP', 'Informe Tecnico (autoridad competente)', 1, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (25, 'RAC', 'Resolucion Autoridad Competente', 1, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (26, 'CACP', 'Certificado (AESAN) -modelos-', 1, 0, 1);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (27, 'OFP', 'Otros Ficheros', 1, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (28, 'AP', 'BOE AG', 1, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (29, 'DEEMMP', 'Docs de otros EEMM', 1, 1, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (30, 'TASAP', 'Tasas', 1, 0, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (31, 'ENMAS', 'Envio Masivo', null, null, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (32, 'DIDT', 'Doc. Producto Firma AECOSAN', 1, 0, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (33, 'DROK', 'Doc modificacion OK -modelo-', 1, 0, 0);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (34, 'MIGIND', 'Migración Documentación Industrias', 0, 0, 1);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (35, 'MIGPRO', 'Migración Documentación Productos', 1, 0, 1);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (37, 'VALAC', 'Valoración Autoridad Competente', 1, 1, 1);
INSERT INTO TYPES_DOCUMENTS (ID, TYPE, NAME, TYPE_COMPANY_PRODUCT, VISIBLE_CCAA, NO_DELETE) VALUES (38, 'acuse de recibo', 'Acuse de recibo', 1, 1, 0);



-- COUNTRIES
/*
INSERT INTO COUNTRIES (ID, NAME, ENROLLMENT, NO_DELETE) VALUES  (1, 'España', 'ES', 0, 1 );
INSERT INTO COUNTRIES (ID, NAME, ENROLLMENT, NO_DELETE) VALUES  (2, 'Alemania', 'DE', 0, 1 );
INSERT INTO COUNTRIES (ID, NAME, ENROLLMENT, NO_DELETE) VALUES  (4, 'Fuera de la Unión Europea', 'UE', 0, 1 );
INSERT INTO COUNTRIES (ID, NAME, ENROLLMENT, NO_DELETE) VALUES  (99, 'Ninguno', 'NIN', 0, 1 );
*/

INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (99, 'NIN', 'Ninguno', 1);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (1, 'ES', 'España', 1);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (2, 'DE', 'Alemania', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (3, 'FR', 'Francia', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (4, 'UE', 'Fuera de la Unión Europea', 1);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (5, 'BE', 'Bélgica', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (6, 'BG', 'Bulgaria', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (7, 'DK', 'Dinamarca', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (8, 'FI', 'Finlandia', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (9, 'GA', 'Grecia', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (10, 'NL', 'Países Bajos', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (11, 'HN', 'Hungría', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (12, 'IE', 'Irlanda', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (13, 'IT', 'Italia', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (14, 'LX', 'Luxemburgo', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (15, 'PL', 'Polonia', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (16, 'PT', 'Portugal', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (17, 'UK', 'Reino Unido', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (18, 'CY', 'Chipre', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (19, 'SI', 'Eslovenia', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (20, 'EE', 'Estonia', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (21, 'LV', 'Letonia', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (22, 'LT', 'Lituania', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (23, 'MT', 'Malta', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (24, 'CZ', 'República Checa', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (25, 'SK', 'República Eslovaca', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (26, 'RO', 'Rumanía', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (27, 'SU', 'Suecia', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (28, 'AT', 'Austria', 0);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (100, 'UE', 'Fabricado en la UE', 1);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (101, 'NP', 'No figura País', 1);
INSERT INTO COUNTRIES (ID, ENROLLMENT, NAME, NO_DELETE) VALUES (102, 'HR', 'Croacia', 0);


-- CCAA

INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'AND', 'Andalucía', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'ARA', 'Aragón', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'AST', 'Asturias', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'BAL', 'Balears, Illes', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'CAN', 'Canarias', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'CAT', 'Cataluña', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'CEU', 'Ceuta', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'CLM', 'Castilla-La Mancha', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'CNT', 'Cantabria', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'CYL', 'Castilla y León', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'EUS', 'País Vasco', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'EXT', 'Extremadura', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'GAL', 'Galicia', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'MAD', 'Madrid', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'MEL', 'Melilla', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'MUR', 'Murcia', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'NAV', 'Navarra', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'RIO', 'La Rioja', 1);
INSERT INTO CCAA (ID, ENROLLMENT, NAME, COUNTRY_ID) VALUES (SEQ_CCAA.NEXTVAL, 'VAL', 'Comunidad Valenciana', 1);

-- PROVINCES

INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'SG', 'Segovia', '40', 'AGENCIA DE PROTECCIÓN DE LA SALUD Y SEGURIDAD ALIMENTARIA&SERVICIO DE ORDENACION Y AUTORIZACIONES SANITARIAS&Pº de Zorrilla, 1&47071 - VALLADOLID', 10);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'SE', 'Sevilla', '41', 'SUBDIRECCIÓN DE PROTECCIÓN DE LA SALUD&SECRETARIA GENERAL DE SALUD PÚBLICA Y PARTICIPACIÓN&Av. de la Innovación s/n (Edif. Arena 1)&41020 - SEVILLA', 1);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'SO', 'Soria', '42', 'AGENCIA DE PROTECCIÓN DE LA SALUD Y SEGURIDAD ALIMENTARIA&SERVICIO DE ORDENACION Y AUTORIZACIONES SANITARIAS&Pº de Zorrilla, 1&47071 - VALLADOLID', 10);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'T', 'Tarragona', '43', 'AREA DE AUTORIZACIONES Y REGISTROS&DIVISIÓN DE GESTIÓN DE RIESGOS&AGENCIA DE PROTECCIÓN DE LA SALUD&C/ Roc de Boronat 81-9508005 - BARCELONA', 6);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'TE', 'Teruel', '44', 'DEPARTAMENTO DE SALUD Y CONSUMO&DIRECCIÓN GENERAL DE SALUD PÚBLICA&C/ Vía Universitas, 36&50017 - ZARAGOZA', 2);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'TO', 'Toledo', '45', 'SERVICIO DE SANIDAD ALIMENTARIA&DIRECCIÓN GENERAL DE SALUD PÚBLICA Y PARTICIPACIÓN&Av. de Francia, 4&45005 - TOLEDO', 8);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'VA', 'Valladolid', '47', 'AGENCIA DE PROTECCIÓN DE LA SALUD Y SEGURIDAD ALIMENTARIA&SERVICIO DE ORDENACION Y AUTORIZACIONES SANITARIAS&Pº de Zorrilla, 1&47071 - VALLADOLID', 10);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'BI', 'Bizkaia', '48', 'DIRECCIÓN DE SALUD PÚBLICA&DEPARTAMENTO DE SANIDAD Y CONSUMO&C/ Donostia-San Sebastián, 1&01010 - VITORIA (ALAVA)', 11);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'ZA', 'Zamora', '49', 'AGENCIA DE PROTECCIÓN DE LA SALUD Y SEGURIDAD ALIMENTARIA&SERVICIO DE ORDENACION Y AUTORIZACIONES SANITARIAS&Pº de Zorrilla, 1&47071 - VALLADOLID', 10);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'Z', 'Zaragoza', '50', 'DEPARTAMENTO DE SALUD Y CONSUMO&DIRECCIÓN GENERAL DE SALUD PÚBLICA&C/ Vía Universitas, 36&50017 - ZARAGOZA', 2);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'MA', 'Málaga', '29', 'SUBDIRECCIÓN DE PROTECCIÓN DE LA SALUD&SECRETARIA GENERAL DE SALUD PÚBLICA Y PARTICIPACIÓN&Av. de la Innovación s/n (Edif. Arena 1)&41020 - SEVILLA', 1);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'BA', 'Badajoz', '06', 'DIRECCIÓN GENERAL DE SALUD PÚBLICA&CONSEJERÍA DE SANIDAD Y DEPENDENCIA&Av. de las Américas 1&06800 - MERIDA (BADAJOZ)', 12);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'TF', 'Santa Cruz de Tenerife', '38', 'DIRECCIÓN GENERAL DE SALUD PÚBLICA&SERVICIO DE SEGURIDAD ALIMENTARIA&Rambla de Santa Cruz, 53&38006 - SANTA CRUZ DE TENERIFE', 5);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'V', 'Valencia/València', '46', 'ÁREA DE SEGURIDAD ALIMENTARIA&DIRECCIÓN GENERAL DE SALUD PÚBLICA&Micer Mascó, 31-33&46010 - VALENCIA', 19);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'GE', 'Girona *', '17', 'AREA DE AUTORIZACIONES Y REGISTROS&DIVISIÓN DE GESTIÓN DE RIESGOS&AGENCIA DE PROTECCIÓN DE LA SALUD&C/ Roc de Boronat 81-9508005 - BARCELONA', 6);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'OR', 'Ourense *', '32', 'SUBDIRECCIÓN GENERAL DE PROGRAMAS&DE CONTROL DE RIESGOS AMBIENTALES PARA LA SALUD&DIRECCIÓN GENERAL DE SALUD PÚBLICA&Edif. Administrativo San Lázaro s/n&15703 - SANTIAGO DE COMPOSTELA (A CORUÑA)', 13);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'PM', 'Palma de Mallorca *', '07', 'UNIDAD DE AUTORIZACIONES&DIRECCIÓN GENERAL DE SALUD PÚBLICA Y PARTICIPACIÓN&Cecili Metel, 18&07003 - PALMA (BALEARES)', 4);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'C', 'Coruña, A', '15', 'SUBDIRECCIÓN GENERAL DE PROGRAMAS&DE CONTROL DE RIESGOS AMBIENTALES PARA LA SALUD&DIRECCIÓN GENERAL DE SALUD PÚBLICA&Edif. Administrativo San Lázaro s/n&15703 - SANTIAGO DE COMPOSTELA (A CORUÑA)', 13);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'VI', 'Araba/Álava', '01', 'DIRECCIÓN DE SALUD PÚBLICA&DEPARTAMENTO DE SANIDAD Y CONSUMO&C/ Donostia-San Sebastián, 1&01010 - VITORIA (ALAVA)', 11);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'AB', 'Albacete', '02', 'SERVICIO DE SANIDAD ALIMENTARIA&DIRECCIÓN GENERAL DE SALUD PÚBLICA Y PARTICIPACIÓN&Av. de Francia, 4&45005 - TOLEDO', 8);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'A', 'Alicante/Alacant', '03', 'ÁREA DE SEGURIDAD ALIMENTARIA&DIRECCIÓN GENERAL DE SALUD PÚBLICA&Micer Mascó, 31-33&46010 - VALENCIA', 19);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'AL', 'Almería', '04', 'SUBDIRECCIÓN DE PROTECCIÓN DE LA SALUD&SECRETARIA GENERAL DE SALUD PÚBLICA Y PARTICIPACIÓN&Av. de la Innovación s/n (Edif. Arena 1)&41020 - SEVILLA', 1);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'AV', 'Ávila', '05', 'AGENCIA DE PROTECCIÓN DE LA SALUD Y SEGURIDAD ALIMENTARIA&SERVICIO DE ORDENACION Y AUTORIZACIONES SANITARIAS&Pº de Zorrilla, 1&47071 - VALLADOLID', 10);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'IB', 'Islas Baleares', '07', 'UNIDAD DE AUTORIZACIONES&DIRECCIÓN GENERAL DE SALUD PÚBLICA Y PARTICIPACIÓN&Cecili Metel, 18&07003 - PALMA (BALEARES)', 4);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'B', 'Barcelona', '08', 'AREA DE AUTORIZACIONES Y REGISTROS&DIVISIÓN DE GESTIÓN DE RIESGOS&AGENCIA DE PROTECCIÓN DE LA SALUD&C/ Roc de Boronat 81-9508005 - BARCELONA', 6);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'BU', 'Burgos', '09', 'AGENCIA DE PROTECCIÓN DE LA SALUD Y SEGURIDAD ALIMENTARIA&SERVICIO DE ORDENACION Y AUTORIZACIONES SANITARIAS&Pº de Zorrilla, 1&47071 - VALLADOLID', 10);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'CC', 'Cáceres', '10', 'DIRECCIÓN GENERAL DE SALUD PÚBLICA&CONSEJERÍA DE SANIDAD Y DEPENDENCIA&Av. de las Américas 1&06800 - MERIDA (BADAJOZ)', 12);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'CA', 'Cádiz', '11', 'SUBDIRECCIÓN DE PROTECCIÓN DE LA SALUD&SECRETARIA GENERAL DE SALUD PÚBLICA Y PARTICIPACIÓN&Av. de la Innovación s/n (Edif. Arena 1)&41020 - SEVILLA', 1);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'CS', 'Castellón/Castelló', '12', 'ÁREA DE SEGURIDAD ALIMENTARIA&DIRECCIÓN GENERAL DE SALUD PÚBLICA&Micer Mascó, 31-33&46010 - VALENCIA', 19);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'CE', 'Ceuta', '51', 'CONSEJERIA DE SANIDAD Y CONSUMO&SECCIÓN DE INSPECCIÓN VETERINARIA&Ctra. San Amaro s/n&51001 - CEUTA', 7);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'CR', 'Ciudad Real', '13', 'SERVICIO DE SANIDAD ALIMENTARIA&DIRECCIÓN GENERAL DE SALUD PÚBLICA Y PARTICIPACIÓN&Av. de Francia, 4&45005 - TOLEDO&', 8);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'CO', 'Córdoba', '14', 'SUBDIRECCIÓN DE PROTECCIÓN DE LA SALUD&SECRETARIA GENERAL DE SALUD PÚBLICA Y PARTICIPACIÓN&Av. de la Innovación s/n (Edif. Arena 1)&41020 - SEVILLA', 1);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'CU', 'Cuenca', '16', 'SERVICIO DE SANIDAD ALIMENTARIA&DIRECCIÓN GENERAL DE SALUD PÚBLICA Y PARTICIPACIÓN&Av. de Francia, 4&45005 - TOLEDO', 8);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'GI', 'Girona', '17', 'AREA DE AUTORIZACIONES Y REGISTROS&DIVISIÓN DE GESTIÓN DE RIESGOS&AGENCIA DE PROTECCIÓN DE LA SALUD&C/ Roc de Boronat 81-9508005 - BARCELONA', 6);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'GR', 'Granada', '18', 'SUBDIRECCIÓN DE PROTECCIÓN DE LA SALUD&SECRETARIA GENERAL DE SALUD PÚBLICA Y PARTICIPACIÓN&Av. de la Innovación s/n (Edif. Arena 1)&41020 - SEVILLA', 1);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'GU', 'Guadalajara', '19', 'SERVICIO DE SANIDAD ALIMENTARIA&DIRECCIÓN GENERAL DE SALUD PÚBLICA Y PARTICIPACIÓN&Av. de Francia, 4&45005 - TOLEDO', 8);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'SS', 'Gipuzkoa', '20', 'DIRECCIÓN DE SALUD PÚBLICA&DEPARTAMENTO DE SANIDAD Y CONSUMO&C/ Donostia-San Sebastián, 1&01010 - VITORIA (ALAVA)', 11);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'H', 'Huelva', '21', 'SUBDIRECCIÓN DE PROTECCIÓN DE LA SALUD&SECRETARIA GENERAL DE SALUD PÚBLICA Y PARTICIPACIÓN&Av. de la Innovación s/n (Edif. Arena 1)&41020 - SEVILLA', 1);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'HU', 'Huesca', '22', 'DEPARTAMENTO DE SALUD Y CONSUMO&DIRECCIÓN GENERAL DE SALUD PÚBLICA&C/ Vía Universitas, 36&50017 - ZARAGOZA', 2);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'J', 'Jaén', '23', 'SUBDIRECCIÓN DE PROTECCIÓN DE LA SALUD&SECRETARIA GENERAL DE SALUD PÚBLICA Y PARTICIPACIÓN&Av. de la Innovación s/n (Edif. Arena 1)&41020 - SEVILLA', 1);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'LE', 'León', '24', 'AGENCIA DE PROTECCIÓN DE LA SALUD Y SEGURIDAD ALIMENTARIA&SERVICIO DE ORDENACION Y AUTORIZACIONES SANITARIAS&Pº de Zorrilla, 1&47071 - VALLADOLID', 10);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'L', 'Lleida', '25', 'AREA DE AUTORIZACIONES Y REGISTROS&DIVISIÓN DE GESTIÓN DE RIESGOS&AGENCIA DE PROTECCIÓN DE LA SALUD&C/ Roc de Boronat 81-9508005 - BARCELONA', 6);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'LO', 'Rioja, La', '26', 'DIRECCIÓN GENERAL DE SALUD PÚBLICA Y CONSUMO&REGISTRO SANITARIO DE ALIMENTOS&C/ Gran Vía de Juan Carlos I 18&26071 - LOGROÑO - (LA RIOJA)', 18);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'LU', 'Lugo', '27', 'SUBDIRECCIÓN GENERAL DE PROGRAMAS&DE CONTROL DE RIESGOS AMBIENTALES PARA LA SALUD&DIRECCIÓN GENERAL DE SALUD PÚBLICA&Edif. Administrativo San Lázaro s/n&15703 - SANTIAGO DE COMPOSTELA (A CORUÑA)', 13);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'M', 'Madrid', '28', 'SERVICIO DE REGISTROS OFICIALES DE SALUD PÚBLICA&DIRECCIÓN GENERAL DE ORDENACIÓN E INSPECCIÓN&Pº de Recoletos 14, 3ª planta&28001 - MADRID', 14);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'ML', 'Melilla', '52', 'CONSEJERIA DE BIENESTAR SOCIAL Y SANIDAD&DIRECCION GENERAL DE SANIDAD Y CONSUMO&Ctra. Alfonso XIII 52-54&52005 - MELILLA', 15);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'MU', 'Murcia', '30', 'SERVICIO DE SEGURIDAD ALIMENTARIA Y ZOONOSIS&DIRECCIÓN GENERAL DE SALUD PÚBLICA&Ronda de Levante, 11&30008 - MURCIA', 16);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'NA', 'Navarra', '31', 'SECCIÓN DE SALUD ALIMENTARIA&INSTITUTO DE SALUD PÚBLICA&Leyre, 15 Planta Baja&31003 - PAMPLONA (NAVARRA)', 17);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'OU', 'Ourense', '32', 'SUBDIRECCIÓN GENERAL DE PROGRAMAS&DE CONTROL DE RIESGOS AMBIENTALES PARA LA SALUD&DIRECCIÓN GENERAL DE SALUD PÚBLICA&Edif. Administrativo San Lázaro s/n&15703 - SANTIAGO DE COMPOSTELA (A CORUÑA)', 13);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'O', 'Asturias', '33', 'SERVICIO DE CONTROL ALIMENTARIO Y ATENCION AL MEDIO&AGENCIA DE SANIDAD AMBIENTAL Y CONSUMO&Santa Susana, 20 - 2ª planta&33005 - OVIEDO', 3);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'P', 'Palencia', '34', 'AGENCIA DE PROTECCIÓN DE LA SALUD Y SEGURIDAD ALIMENTARIA&SERVICIO DE ORDENACION Y AUTORIZACIONES SANITARIAS&Pº de Zorrilla, 1&47071 - VALLADOLID', 10);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'GC', 'Palmas, Las', '35', 'DIRECCIÓN GENERAL DE SALUD PÚBLICA&SERVICIO DE SEGURIDAD ALIMENTARIA&Alfonso XIII, 4&35003 - LAS PALMAS DE GRAN CANARIA', 5);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'PO', 'Pontevedra', '36', 'SUBDIRECCIÓN GENERAL DE PROGRAMAS&DE CONTROL DE RIESGOS AMBIENTALES PARA LA SALUD&DIRECCIÓN GENERAL DE SALUD PÚBLICA&Edif. Administrativo San Lázaro s/n&15703 - SANTIAGO DE COMPOSTELA (A CORUÑA)', 13);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'SA', 'Salamanca', '37', 'AGENCIA DE PROTECCIÓN DE LA SALUD Y SEGURIDAD ALIMENTARIA&SERVICIO DE ORDENACION Y AUTORIZACIONES SANITARIAS&Pº de Zorrilla, 1&47071 - VALLADOLID', 10);
INSERT INTO PROVINCES (ID, ENROLLMENT, NAME, PRE_POSTAL_CODE, ADDRESS, CCAA_ID) VALUES (SEQ_PROVINCES.NEXTVAL, 'S', 'Cantabria', '39', 'SERVICIO DE SEGURIDAD ALIMENTARIA&DIRECCIÓN GENERAL DE SALUD PÚBLICA&Federico Vial, 13&39009 - SANTANDER (CANTABRIA)', 9);



/*
-- TODO borrar Ejemplo tabla RGSEAA y RGSEAA_ACTIVITY
INSERT INTO COMPANIES (ID, NIF, NAME, STATE) VALUES (1, '000000CIF', 'EJEMPLO 1', 1 );

INSERT INTO ESTABLISHMENTS (ID, COMPANY_ID, ADDRESS, STATE) VALUES (1, 1, 'Calle de la piruleta', 1 );

INSERT INTO RGSEAA (ID, COMPANY_ID, ESTABLISHMENT_ID, KEY_ID, NUM_RGSEAA, STATE) VALUES (1, 1, 1, 1, 123456, 1 );

INSERT INTO RGSEAA_ACTIVITY (ID, RGSEAA_ID, ACTIVITY_KEY_CATEGORY_SUB_ACTIVITY_ID, STATE) VALUES (1, 1, 6, 1 );
---------------------------------------------------
*/